### PR TITLE
feat: Different branch to hook up new compaction algorithm

### PR DESCRIPTION
**Pull request by NGA-TRAN**
I messed up with semantic of #5188 and create this new branch for it

The first commit includes cherry picks of the first 3 commits from #5188 

- [x] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

### CODE REVIEW

**Comment by NGA-TRAN** [comment]
I am trying to understand why test `remote_partition_and_get_from_store_and_pull` fails. The parquet file ID is supposed to be 1 but it is actual 2

**Comment by carols10cents** [comment]
It looks like the compactor is running during an end-to-end test and maybe the test is not expecting that?

```
thread 'end_to_end_cases::cli::remote_partition_and_get_from_store_and_pull' panicked at 'Unexpected stdout, failed (var.contains("id": "1") && var.contains("partitionId": "1",))
├── var as str: [
│     {
│       "id": "2",
│       "sequencerId": "1",
│       "namespaceId": "1",
│       "tableId": "1",
│       "partitionId": "1",
│       "objectStoreId": "d1edf642-a6d0-4741-ad47-2ee3a265eaaf",
│       "minTime": "123456",
│       "maxTime": "123456",
│       "fileSizeBytes": "2188",
│       "rowCount": "1",
│       "compactionLevel": 1,
│       "createdAt": "1658513769463852966",
│       "columnSet": [
│         "1",
│         "2",
│         "3",
│         "4"
│       ]
│     }
│   ]
└── var.contains("id": "1")
└── var.contains("id": "1")
    └── var: [
          {
            "id": "2",
            "sequencerId": "1",
            "namespaceId": "1",
            "tableId": "1",
            "partitionId": "1",
            "objectStoreId": "d1edf642-a6d0-4741-ad47-2ee3a265eaaf",
            "minTime": "123456",
            "maxTime": "123456",
            "fileSizeBytes": "2188",
            "rowCount": "1",
            "compactionLevel": 1,
            "createdAt": "1658513769463852966",
            "columnSet": [
              "1",
              "2",
              "3",
              "4"
            ]
          }
        ]
```

**Comment by NGA-TRAN** [comment]
Yes, that is what I am thinking. This kind of test is new to me and I need to figure out how to change the test to make it works as expected

**Comment by NGA-TRAN** [comment]
I am not sure change 1 to 2 will provide a deterministic expectation

**Comment by carols10cents** [comment]
I'm going to merge main into this branch to get the compaction of 1 file change in

**Comment by carols10cents** [comment]
oh wait I was on the wrong branch

**Comment by NGA-TRAN** [comment]
@carols10cents : it looks like 2 is the deterministic value. Can you have a quick review to see if I miss anything?

**Comment by carols10cents** [comment]
Seems ok if you're ok with testing that compaction ran here!

**Review by carols10cents — APPROVED** [review]

**Pull request merged**
