### PR TITLE
feat: Add observer interactive CLI command

### PR DESCRIPTION
**Pull request by alamb**
This PR contains code for an internal tool I wrote that I plan to use to inspect a IOx server using an interactive SQL command prompt. 

I am not sure I want to propose actually merging this to IOx (yet) but I did want a place for the code to live and to start 
a discussion about if this might be useful to have.

# example

```
cargo run -p observer
...
> select database_name, storage, count(*) as num_chunks, sum(estimated_bytes)/1024/1024 as estimated_mb
from chunks
group by database_name, storage
order by estimated_mb desc;

+-----------------------------------+---------------------+------------+--------------+
| database_name                     | storage             | num_chunks | estimated_mb |
+-----------------------------------+---------------------+------------+--------------+
| 844910ece80be8bc_7be09b71c487d5d3 | ClosedMutableBuffer | 78         | 838          |
| 7f4b06e9112d7bc8_system%5Fusage   | ClosedMutableBuffer | 2          | 20           |
| 844910ece80be8bc_5403ba1b2193d41f | ClosedMutableBuffer | 2          | 20           |
| 7f4b06e9112d7bc8_system%5Fusage   | OpenMutableBuffer   | 1          | 8            |
| 844910ece80be8bc_4bed41a6ff7f0ee0 | OpenMutableBuffer   | 1          | 6            |
| 844910ece80be8bc_5403ba1b2193d41f | OpenMutableBuffer   | 1          | 4            |
| 844910ece80be8bc_eaec8df57a81a1e9 | OpenMutableBuffer   | 1          | 3            |
| InfluxData_%5Ftasks               | OpenMutableBuffer   | 1          | 1            |
| 844910ece80be8bc_05d1e95653672000 | OpenMutableBuffer   | 1          | 1            |
| 844910ece80be8bc_cac95fa59126cd01 | OpenMutableBuffer   | 1          | 0            |
| 844910ece80be8bc_dfeaf11d9d194efd | OpenMutableBuffer   | 1          | 0            |
| 844910ece80be8bc_a44813fabdadbc9d | OpenMutableBuffer   | 1          | 0            |
| 844910ece80be8bc_677a8b3438917830 | OpenMutableBuffer   | 1          | 0            |
| 844910ece80be8bc_81c1fce8c36339dc | OpenMutableBuffer   | 1          | 0            |
| 844910ece80be8bc_05ca7bca3d2e1000 | OpenMutableBuffer   | 1          | 0            |
| 844910ece80be8bc_16657ffd05d7d16c | OpenMutableBuffer   | 1          | 0            |
| 844910ece80be8bc_7caaf9613b16e7c2 | OpenMutableBuffer   | 1          | 0            |
| 844910ece80be8bc_ea96994e53c36625 | OpenMutableBuffer   | 1          | 0            |
| 844910ece80be8bc_f34028c22e8b8b37 | OpenMutableBuffer   | 1          | 0            |
| 844910ece80be8bc_05a8439769860000 | OpenMutableBuffer   | 1          | 0            |
| 844910ece80be8bc_05a7a51565539000 | OpenMutableBuffer   | 1          | 0            |
| 844910ece80be8bc_84cc8db6499a3d11 | OpenMutableBuffer   | 1          | 0            |
| 844910ece80be8bc_3c0bd4c89186ca89 | OpenMutableBuffer   | 2          | 0            |
| 844910ece80be8bc_5d5a6ade9b665dfc | OpenMutableBuffer   | 1          | 0            |
+-----------------------------------+---------------------+------------+--------------+
24 rows in set. Query took 0 seconds.

```

- [x] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

### CODE REVIEW

**Comment by tustvold** [comment]
Not looked in detail at the code yet, but I wouldn't be against making the repl part of the standard CLI - e.g. `influxdb_iox console` or something...

**Comment by alamb** [comment]
> but I wouldn't be against making the repl part of the standard CLI - e.g. influxdb_iox console or something...

**Comment by alamb** [comment]
Related to https://github.com/influxdata/influxdb_iox/issues/977

**Comment by alamb** [comment]
Superceded by https://github.com/influxdata/influxdb_iox/pull/1349

**Pull request closed without merging**
