### PR TITLE
chore: Update datafusion again

### PR DESCRIPTION
**Pull request by alamb**
# Rationale
* Get https://github.com/apache/arrow-datafusion/pull/2091 (which is part of making DataFusion work better with multi tenancy)

# Changes
1. Update to https://github.com/apache/arrow-datafusion/commit/9e3bec811549b61bcb7957554879b77fd9c249ef
2. Updates for those changes (including changes from the following PRs)

### CODE REVIEW

**Comment by alamb** [comment]
We appear to have hit a bug in the case evaluation

```

}'
thread 'IOx Query Executor Thread' panicked at 'range end index 3 out of range for slice of length 2', /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-11.0.0/src/array/transform/primitive.rs:31:37
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::slice::index::slice_end_index_len_fail
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/slice/index.rs:43:5
   3: <core::ops::range::Range<usize> as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/slice/index.rs:245:13
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/slice/index.rs:15:9
   5: arrow::array::transform::primitive::build_extend::{{closure}}
             at /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-11.0.0/src/array/transform/primitive.rs:31:37
   6: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/alloc/src/boxed.rs:1868:9
   7: arrow::array::transform::MutableArrayData::extend
             at /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-11.0.0/src/array/transform/mod.rs:646:9
   8: datafusion_physical_expr::physical_expr::scatter::{{closure}}
             at /Users/alamb/.cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/2d6addd/datafusion-physical-expr/src/physical_expr.rs:107:9
   9: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/iter/traits/iterator.rs:733:29
  10: core::iter::traits::iterator::Iterator::fold
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/iter/traits/iterator.rs:2171:21
  11: core::iter::traits::iterator::Iterator::for_each
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/iter/traits/iterator.rs:736:9
  12: datafusion_physical_expr::physical_expr::scatter
             at /Users/alamb/.cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/2d6addd/datafusion-physical-expr/src/physical_expr.rs:100:5
  13: datafusion_physical_expr::physical_expr::PhysicalExpr::evaluate_selection
```

Likely introduced in https://github.com/apache/arrow-datafusion/pull/2068

**Comment by yjshen** [comment]
I noticed this last night but haven't reproduced it in DataFusion with tests. I will try to dig deeper today.

**Comment by alamb** [comment]
Thanks for the hint @yjshen  -- I also had not had luck reproducing this in DataFusion only. I'll plan to look into this more carefully today.

**Comment by alamb** [comment]
> It seems I'm hitting a SlicesIterator bug here 🤔: (run with test influxrpc::read_group::test_grouped_series_set_plan_group_field_pred_filter_on_value_sum)


I think the issue is that SlicesIterator doesn't look for / respect nulls. I will see if I can cook up a reproducer.

**Comment by alamb** [comment]
Filed https://github.com/apache/arrow-datafusion/issues/2117 for the upstream DataFusion issue. I will have a fix shortly

**Comment by alamb** [comment]
Updated to include https://github.com/apache/arrow-datafusion/pull/2118

**Review by crepererum — APPROVED** [review]

**Pull request merged**
