### PR TITLE
feat: compactor sharding

### PR DESCRIPTION
**Pull request by crepererum**
I'm not saying we have to use this, but this is a demonstration how easy it would be to add sharding to the compaction tier and also acts as a "backup / insurance" if we ever need it.

### CODE REVIEW

**Comment by NGA-TRAN** [comment]
Since @Marco has this PR available, let us pull @pauldix and @jacobmarble in.

**Summary: we can setup many compactors to deal with large workload clusters as needed**

Context. From [compactor dashboard](https://grafana.prod01-eu-central-1.aws.influxdata.io/d/TLwmy7Z9fh/compactor2?orgId=1), we compact 25 partitions/second (does this include the partitions we skipped due to timeout and/or too large, @crepererum?). This means we compact 25 * 60  * 10 = 15K partitions per 10 minutes. However, there are 25K new partitions needed to compact every 10 minutes. The more we behind, the more files in the partitions and the higher chance we will skip compacting them because they have so many files. This will lead to to compactor just iterates but compact very few partitions just like we see 10 days after we deploy kafkaless Ingester2.

When the [algorithm iteration](https://github.com/influxdata/idpe/issues/16983) for hot and cold are at some good optimized level (in a few or several days), we expect the number of partitions/second will increase a few times and may meet the demand of eu-central-1.  However, Marco and I have talked and Marco demonstrates in this PR that it is very easy to add more compactors, and that we use 3 ingesters to ingests tons of files, we may think about setting up a few compactors to deal with **large workload  of certain cluster** while we work on dealing with the new kafkaless ingester design.

**Review by NGA-TRAN — APPROVED** [review]
I approve this because they has no value and no effect yet. We will use config params to make a multiple-compactor cluster as needed

**Comment by pauldix** [comment]
Longer term I think it would be better to have a work queue with a dynamically sized pool of workers, but I think this is a good quick fix to get some scale up for clusters that have too many partitions to compact in the interim.

**Comment by crepererum** [comment]
> Longer term I think it would be better to have a work queue with a dynamically sized pool of workers, but I think this is a good quick fix to get some scale up for clusters that have too many partitions to compact in the interim.

Good point, filed #6749.

**Pull request merged**
