### PR TITLE
feat: Add support for ready API to influxdb_client

### PR DESCRIPTION
**Pull request by aakashhemadri**
Get the readiness of an instance at startup

Signed-off-by: Aakash Hemadri <aakashhemadri123@gmail.com>

I intend to contribute to influxdb2_client api's. Starting with `/ready` here.
I am not sure as to how Responses are to be handled, for the sake of the PR I have returned the reponse as text. Pointers on that what is expected would be helpful :)

I have created a test and example for the api.
Linted with rustfmt and ran clippy as well.

- [x] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

### CODE REVIEW

**Comment by alamb** [comment]
Thanks @aakashhemadri  -- we'll check this out tomorrow!

**Review by alamb — COMMENTED** [review]
The code looks good to me -- @tustvold  / @domodwyer  do you have any thoughts about this pattern (the client returning the text of the Ready response)? Would you prefer a more structured approach?

Unless anyone objects I suggest we take this PR and can file subsequent tickets / issues to track more structured responses (if desired).

Thanks again @aakashhemadri

**Comment by aakashhemadri** [comment]
Hey @alamb the thing is we already have setup and health api in the same stage as this PR while we are WIP on query and label, we would like further consensus on what would be preferred to move forward with the rest of the incomplete API. If everyone is happy with simple Response text (I doubt they would) then okay, but if any of the more well versed members of rust could point us to more robust patterns we are willing to work on this and include it in this and other PRs. Thanks :)

**Comment by aakashhemadri** [comment]
If there are any other probable refactoring -- maybe splitting lib.rs or writing integration tests or other such suggestions we are willing to write PRs and improving the same.
@alamb

**Comment by carols10cents** [comment]
It looks like the [Go InfluxDB2 client returns a `bool` from the `Ready` function?](https://github.com/influxdata/influxdb-client-go/blob/bfe8bb2634da81520bda469bc030d3af12a56bf6/client.go#L135-L145)

**Comment by alamb** [comment]
@aakashhemadri  can you please make the response follow the Go client (return a bool)?

I will add in some clarifying text / guidelines as well in a follow on PR to make this clearer.

Thanks!

**Comment by aakashhemadri** [comment]
> @aakashhemadri can you please make the response follow the Go client (return a bool)?
> 
> I will add in some clarifying text / guidelines as well in a follow on PR to make this clearer.
> 
> Thanks!

@alamb @carols10cents Sure! Will follow the go client and push my updates :)
Thanks!

**Comment by aakashhemadri** [comment]
I noticed that for the other api's go client returns json, Shall I create structs for this purpose and serialize with serde_json? ot shall I use the serde_json::Value type.. not sure about this, first time working with serde :) Or shall I default to return text? @alamb @carols10cents

**Comment by aakashhemadri** [comment]
I also noticed that the influxdb_iox_client the src/client/ heirarchy, would it be ideal to follow the same structure to put up a refactor PR? @alamb 

Sorry for the onslaught of questions 😅 
Thanks again!

**Comment by alamb** [comment]
@aakashhemadri 
> I noticed that for the other api's go client returns json, Shall I create structs for this purpose and serialize with serde_json? or shall I use the serde_json::Value type.. not sure about this,

I recommend creating a Rust struct and serializing with `serde` -- I think this is the most 'Rust Idiomatic -- as Rust is strongly typed and users of this library will probably expect to get typed values back. 

> I also noticed that the influxdb_iox_client the src/client/ heirarchy, would it be ideal to follow the same structure?

The reason `influxdb_iox_client` (which uses gRPC) has a `src/client` hierarchy is that it has several distinct client types (`management::Client`, `write::Client`, etc). Unless the influxdb_client ends up with a similar type hierarchy I don't think there is any need to move the files around

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
I verified that the CLA has been properly registered. Thanks again @aakashhemadri !

**Comment by aakashhemadri** [comment]
Not sure what happened here... I just deleted the branch thinking the commit was merged, and synced main to upstream/main

**Comment by alamb** [comment]
No worries @aakashhemadri  -- normally we have the `kodiak` bot do the merging ( that is what the `automerge` labels do). However, github actions was having issues yesterday so perhaps that screwed things up. 

Please do open a new PR (or else I can as well and cherry-pick your commits)

Thanks again!

**Comment by aakashhemadri** [comment]
> No worries @aakashhemadri -- normally we have the `kodiak` bot do the merging ( that is what the `automerge` labels do). However, github actions was having issues yesterday so perhaps that screwed things up.
> 
> Please do open a new PR (or else I can as well and cherry-pick your commits)
> 
> Thanks again!

Thanks @alamb 
I'll put up a new PR :)

**Pull request closed without merging**
