### PR TITLE
docs: Improve style guide about using Snafu

### PR DESCRIPTION
**Pull request by alamb**
Add a note to the style guide about the magic `as _` seemingly needed to wrap `Box`ed errors for use in Snafu `.context()` calls

This came up in https://github.com/influxdata/influxdb_iox/pull/692#discussion_r563642995 where @e-dard  pointed out this pattern is not obvious

You can see a rendered version of this the doc [here](https://github.com/influxdata/influxdb_iox/blob/alamb/snafu_docs/docs/style_guide.md#use-context-to-wrap-underlying-errors-into-module-specific-errors)

- [x] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

### CODE REVIEW

**Comment by domodwyer** [comment]
Maybe [this](https://docs.rs/snafu/0.6.10/snafu/guide/attributes/index.html#transforming-the-source) will help? The `as _` is a bit... magic!

**Comment by carols10cents** [comment]
> Maybe [this](https://docs.rs/snafu/0.6.10/snafu/guide/attributes/index.html#transforming-the-source) will help? The `as _` is a bit... magic!

I looked into using snafu's `from` attribute, but we have at least one case where the source error is an associated type of a trait on a generic that I don't think it's possible to do with `from` currently; I've extracted a minimal example and added it to [this snafu issue](https://github.com/shepmaster/snafu/issues/123#issuecomment-767085683).

**Review by carols10cents — APPROVED** [review]
LGTM!

**Comment by alamb** [comment]
https://github.com/shepmaster/snafu/issues/123 is a fascinating read; Thanks @carols10cents !

**Review by e-dard — APPROVED** [review]
Nice change

**Pull request merged**
