### PR TITLE
feat: add pre-commit hook

### PR DESCRIPTION
**Pull request by tustvold**
Adds a basic pre-commit githook that runs cargo fmt and re-stages formatted files that were previously staged

### CODE REVIEW

**Comment by domodwyer** [comment]
There's already hooks in conductor that covers:

* check
* fmt
* test
* clippy

Perhaps we use that for consistency across the projects? It also only runs on changed files, and has a snazzy output.

It also covers:

* checks all JSON/YAML files are valid
* shells scripts have shebangs
* ensures no merge conflict markers are committed
* some other nice to have stuff

We can pick and choose for whatever makes sense here

**Comment by tustvold** [comment]
I will take a look on Monday, this was definitely a "something is better than nothing" deal, but if there is something better I'm all for it.

**Review by alamb — APPROVED** [review]
Thank you

**Comment by tustvold** [comment]
So I've taken a look at the precommit setup in conductor, and I'm honestly torn. 

Most of the heavier lints, such as clippy and tests, I personally don't want as pre-commit hooks as they interfere with my local git workflow - for example, if I want to temporarily commit my changes before a refactor I don't want to have to build and run the test suite. But some of the lighter-weight lints are certainly more compelling.

However, the need to install a third-party python package which then downloads and runs scripts from other git repositories seems a little bit too heavy. I'm no fan of bash, but I can't help feeling our pre-commit requirements don't warrant an entire toolchain to manage them...

I'd personally be inclined just to stick with something simple like this, but I don't really have strong opinions.

**Comment by domodwyer** [comment]
Clippy as a lint is... cheap. You definitely get a good bang-for-buck ratio on that one. Tests definitely not need to be included, personal choice per project 👍 

I understand why having a tool to manage the pre-commit might be 'heavy' but honestly - what dev doesn't have python?! And it's the python code that makes the solution a one up over a simple bash pre-commit, like only running against changed files and only running "rust" lints if rust code changes.

**Comment by tustvold** [comment]
I think there is too much personal taste involved here to reach a reasonable consensus

**Pull request closed without merging**
