### PR TITLE
feat: Derive serde for protos

### PR DESCRIPTION
**Pull request by mkmik**
Rationale
---------

Our CLI needs to be able to accept configuration as JSON and render configuration as JSON.

Protobufs technically have an official JSON encoding rule called 'jsonpb` but prost doesn't
offer native supprot for it.

`prost` allows us to specify arbitrary derive metadata to be added to generated
code. We emit the `serde` derive directives in the two packages that generate prost code
(`generated_types` and `google_types`).

We use the `serde(rename_all = "camelCase")` to approximate `jsonpb`.

We instruct `prost` to use `bytes::Bytes` for some types, hence we must turn on the `serde` feature
on the `bytes` dependency.

We also use json to serialize the output of the `database get` command, to showcase the feature
and get rid of a TODO. In a subsequent PR I'll teach `database create` (and the yet to be done `database update`) to accept an option JSON configuration body so we can configure partitioning, lifecycle, sharding etc rules etc.

Caveats
-------

This is not technically `jsonpb`. Main issues:
1. default values not omitted
2. no special rendering of special types like `google.protobuf.Any`

Future work
-----------

Figure out if we can get fully compliant `jsonpb`, or at least a decent approximation.

Effect
------

```console
$ cargo run -- database get foobar_weather
{
  "name": "foobar_weather",
  "partitionTemplate": {
    "parts": [
      {
        "part": {
          "time": "%Y-%m-%d %H:00:00"
        }
      }
    ]
  },
  "lifecycleRules": {
    "mutableLingerSeconds": 0,
    "mutableMinimumAgeSeconds": 0,
    "mutableSizeThreshold": 0,
    "bufferSizeSoft": 0,
    "bufferSizeHard": 0,
    "sortOrder": {
      "order": 2,
      "sort": {
        "createdAtTime": {}
      }
    },
    "dropNonPersisted": false,
    "immutable": false
  },
  "walBufferConfig": null,
  "shardConfig": {
    "specificTargets": null,
    "hashRing": null,
    "ignoreErrors": false
  }
}
```

### CODE REVIEW

**Comment by tustvold** [comment]
It's worth noting this will also encode enumerations as integers not strings.

I'm torn on this, I don't think accepting JSON input for the CLI is a good idea, but agree JSON output is important. I was somewhat planning to punt on this until prost added jsonpb support and use that then - is there a reason we need this now?

**Comment by mkmik** [comment]
> It's worth noting this will also encode enumerations as integers not strings.

Yeah, there are a few issues like that. Do we want to be perfect from day zero or do we have some leeway until we cut a public release?

> 
> I'm torn on this, I don't think accepting JSON input for the CLI is a good idea, but agree JSON output is important. I was somewhat planning to punt on this until prost added jsonpb support and use that then - is there a reason we need this now?

While writing the sharding config CLI I didn't feel comfortable duplicating the whole sharding config with flags, subcommands or some other contraption.

There are also other database configuration options that we may want to set while we use iox internally. We don't have to use the CLI yet, we could use grpcurl, but I wanted to give a stab at asymptomatically getting to jsonpb support (either contributing upstream or hacking it up while waiting)

**Review by alamb — APPROVED** [review]
I think this is good enough for now and I don't see any plausible alternatives to get the CLI for manipulating databases working quickly. 

I recommend filing a ticket in influxdb_iox for switching the CLI input and output to use `jsonpb` when the underlying libraries add support (and mentioning stuff like the `enum` -> `int` encoding so that we don't forget)

**Comment by mkmik** [comment]
> I think this is good enough for now and I don't see any plausible alternatives to get the CLI for manipulating databases working quickly.
> 
> I recommend filing a ticket in influxdb_iox for switching the CLI input and output to use `jsonpb` when the underlying libraries add support (and mentioning stuff like the `enum` -> `int` encoding so that we don't forget)

Ticket created: #1075

**Pull request merged**
