### PR TITLE
refactor: Change ReadBuffer column_names to return Option<BTreeSet>

### PR DESCRIPTION
**Pull request by alamb**
This is part of the "making tag_column_names work in gRPC"  https://github.com/influxdata/influxdb_iox/issues/791

# Rationale:
Follows the model set in https://github.com/influxdata/influxdb_iox/pull/776 where the `ReadBuffer` responds to metadata queries with the native Rust types and the conversion to `RecordBatch` is done higher up (in the planner).

This rationale for that design is to allow efficient merging known good results across chunks without running an entire plan

# Changes

Change ReadBuffer `column_names` to return `Option<BTreeSet>` and update tests.

- [x] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

### CODE REVIEW

**Review by carols10cents — APPROVED** [review]

**Review by domodwyer — APPROVED** [review]
👍

**Comment by alamb** [comment]
FYI @e-dard

**Comment by alamb** [comment]
Yay! 🎉

**Comment by e-dard** [comment]
🎉

**Pull request merged**
