### PR TITLE
chore: Upgrade rust to nightly-2021-02-12

### PR DESCRIPTION
**Pull request by mkmik**
12-02-2021 is a palindrome day in a good part of the world, let's celebrate that with a toolchain upgrade.

### CODE REVIEW

**Comment by mkmik** [comment]
turns out the docker image we use to build has `2020-11-19` baked in (although, stable seems to get updated)
 
```
; docker run -ti --rm quay.io/influxdb/rust:ci rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /usr/local/rustup

installed toolchains
--------------------

nightly-2020-11-19-x86_64-unknown-linux-gnu
1.50.0-x86_64-unknown-linux-gnu (default)

active toolchain
----------------

1.50.0-x86_64-unknown-linux-gnu (default)
rustc 1.50.0 (cb75ad5db 2021-02-10)

```

**Comment by mkmik** [comment]
@domodwyer asked in #800 whether we should  be moving to stable.

I tried to see if it builds on stable, but from what I can see there is at least one dependency that chokes on that:

```
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> /Users/mkm/.cargo/registry/src/github.com-1ecc6299db9ec823/packed_simd_2-0.3.4/src/lib.rs:202:1
    |
202 | / #![feature(
203 | |     repr_simd,
204 | |     rustc_attrs,
205 | |     const_fn,
...   |
215 | |     llvm_asm
216 | | )]
    | |__^
```

**Comment by domodwyer** [comment]
@alamb that dep is `packed_simd_2` which is required by arrow.

`packed_simd_2` is [deprecated](https://github.com/rust-lang/packed_simd#implementation-of-rust-rfc-2366-stdsimd) - [`stdsimd`](https://github.com/rust-lang/stdsimd) appears to be the new hotness.

Is this something we can/should PR to swap? @mkmik is that the only dependency relying on nightly at this point?

**Comment by mkmik** [comment]
> Is this something we can/should PR to swap? @mkmik is that the only dependency relying on nightly at this point?

it's the only error I got when I tried to build with `rust-toolchain` stable; not sure if other would spring up once that one is fixed though.

**Comment by alamb** [comment]
I believe the simd dependency comes from using the `simd` feature of the arrow crate (in addition to any uses of it ourselves)

**Comment by mkmik** [comment]
shaving that yak upstream is probably going to do good though

**Comment by mkmik** [comment]
Let's kill this in favour of #809

**Comment by domodwyer** [comment]
Lets drop the changes from #800 then - the build image has to be pulled for each CI run so we try to keep it small

**Pull request closed without merging**
