### PR TITLE
test: Reproducer for #3428

### PR DESCRIPTION
**Pull request by alamb**
Add some test for influxrpc queries demonstrating incorrect results due to #3428

### CODE REVIEW

**Comment by e-dard** [comment]
These tests seem to be passing according to CI. Do you still want this reviewed and merged?

**Comment by alamb** [comment]
> These tests seem to be passing according to CI. Do you still want this reviewed and merged?


Yes, please @e-dard  -- the tests are passing bc the wrong answers are checked in

I just figured I would write the test

**Comment by e-dard** [comment]
Ah ok. I'll look through it.

An alternative way to do it would be to check-in the expected correct answers and then add the `#[ignore]` attribute, which should ensure CI passes.

**Comment by alamb** [comment]
> An alternative way to do it would be to check-in the expected correct answers and then add the #[ignore] attribute, which should ensure CI passes.

that is fine with me too -- whichever you would prefer

**Review by e-dard — APPROVED** [review]

**Pull request merged**
