### PR TITLE
feat: remove serde from data types

### PR DESCRIPTION
**Pull request by tustvold**
~~_This is currently blocked on #2633 but I have had it sitting in a branch for a while so thought I'd put it into a draft PR._~~

Now that pbjson can provide a stable serialization of our protobufs, we no longer need to serialize data_types. By removing this support not only do we save some compile time, but we avoid accidentally using a non-stable serialization format for things that might actually want or need stability, and/or the ability to evolve in API-compatible ways.

This was added in #2130 and I'm not entirely sure how conductor is making use of this, if it even is. However, following the extensive discussions on #2409 I'm fairly confident there is no correct way to use this serialization, as the data_types are defaulted and don't accurately reflect what was sent over the wire, nor can they accommodate unrecognized or missing fields.

### CODE REVIEW

**Comment by tustvold** [comment]
I have confirmed that conductor makes no mention of `data_types` other than a transitive dependency from `generated_types` which can we can add an option to disable

**Comment by tustvold** [comment]
Following #2739 conductor doesn't even have a transitive dependency on data_types and so I think this is good to go

**Comment by mkmik** [comment]
I think conductor will only ever use json encoding of the protobuf layer (pbjson) and never the internal types

**Review by domodwyer — APPROVED** [review]
Serialising these directly was a semi-usable stop gap to unblock until we had #2409 and the time to decouple everything 👌 

I am unaware of anything needing serde support now.

**Pull request merged**
