### PR TITLE
feat: s3 compatibility storages support

### PR DESCRIPTION
**Pull request by DCjanus**
# Rationale:

My job is develop and host an s3 compatibility storage service in my company, and I do believe this is an common situation for a lot of company, for cost and data security.

To support those storages, custom region name with custom endpoint is required.

# Changes

1. Add `aws_endpoint` argument and environment value to set s3 storage endpoint.

### CODE REVIEW

**Comment by e-dard** [comment]
Hey @DCjanus thanks for this PR. I cannot see your github name `DCJanus` having signed out CLA. It could be that if you only did it recently our system hasn't updated. I'll check later, and If not I might ask you to sign it again.

We will get some eyes on this PR! I'm assuming that this is to add support for things like minio? Can you add a bit of background about what you're looking to achieve with this change? Thanks!

**Comment by DCjanus** [comment]
This is my first time to work with this project, and I thought the checkbox means signed. (Yes, just like most "user agreement", I don't read CLA, this is not good.)

I've read CLA and signed it, and update this PR with little detail.

**Review by pauldix — COMMENTED** [review]
I'll let others comment on the overall PR, but I do have one small request. Can you update `docs/env.example`? We'd like to have any environment variable that can be set mentioned there.

**Comment by DCjanus** [comment]
Hi @pauldix, I've add an example in `docs/env.example`, but I'm not a native speaker, there may be a syntax error in comment part , I may need to ask your help in language part.

And since we live in different time zones, ping-pong like communication might be inefficient, feel free to make any change on my branch.

**Review by alamb — APPROVED** [review]
The code looks good to me. Thank you @DCjanus . The only thing that might make it better is some sort of test. @crepererum  has been talking about more regularly running the integration tests, so perhaps we will have a better testing story shortly.

However, I do think this one is good enough to merge.

**Pull request merged**
