### PR TITLE
docs: Fix wrong test data file path

### PR DESCRIPTION
**Pull request by haoch**
Closes #

Describe your proposed changes here.

- [x] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

### CODE REVIEW

**Comment by alamb** [comment]
Thank you @haoch !

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
The semantic PR feature is setup on this repo, meaning all commit messages need to follow that convention (e.g. `docs: Fix wrong test data file path` rather than `[Docs]: Fix wrong test data file path`

I am happy to fix this if you would like

**Comment by haoch** [comment]
@alamb Thanks. How would like me to fix? Recreate another PR? Or you could squash merge?

**Comment by alamb** [comment]
Hi @haoch  -- the way I would normally fix it would be to `git rebase -i origin/main` and change the commit message via a `'reword'` action

**Comment by haoch** [comment]
@alamb Fixed.

**Comment by alamb** [comment]
Looks great -- thanks again @haoch

**Pull request merged**
