### PR TITLE
fix: avoid spamming the logs with errors that are not errors

### PR DESCRIPTION
**Pull request by alamb**
If you look at the logs from tools [https://logs.aws.influxdata.io/search?q=kubernetes_container_name%3Aiox+AND+log_processed_level%3Aerror&rangetype=relative&relative=7200](link)

Screen Shot 2021-04-06 at 12 21 22 PM

There are many log messages about not being able to evict a chunk, but I don't think that is an error

### CODE REVIEW

**Comment by tustvold** [comment]
I think it is an error - it implies that chunks are not being moved to the read buffer fast enough to match the soft buffer limit that has been set? Perhaps it should instead say such? :thinking:

**Review by tustvold — APPROVED** [review]
Actually I think you're right - this isn't an error, but it will likely cause the server to hit the hard buffer limit at which point it will reject writes, which will be an error

**Comment by alamb** [comment]
@tustvold perhaps there is a deeper problem we should look at (aka "why are there so many of these error messages in the logs")?

**Comment by tustvold** [comment]
> why are there so many of these error messages in the logs

Whenever the memory consumption is above the soft limit it will try to find read buffer candidates to evict. If you misconfigure the lifecycle rules for your workload there will be sufficient data in just the mutable buffer to make it hit this limit and then every second it will complain that it can't find a candidate to evict... I'm not sure what the "correct" behaviour in such a scenario is?

**Comment by alamb** [comment]
> Whenever the memory consumption is above the soft limit it will try to find read buffer candidates to evict. If you misconfigure the lifecycle rules for your workload such that there is sufficient data in just the mutable buffer to make it hit this limit, every second it will complain that it can't find a read buffer candidate to evict... I'm not sure what the "correct" behaviour in such a scenario is?

I think what I was confused about was that the message seemed to be un-actionable -- specifically the "what, if anything, should I do as an administrator in response to seeing this error in the log.

@tustvold what do you think about a `warn!` or something saying "soft limit exceeded, but other lifecycle rules prevent chunks from being evicted"?

**Comment by tustvold** [comment]
@alamb I think a warning saying something along the lines of `soft limited exceeded, but no chunks found that can be evicted" sounds good to me :+1: . It identifies that this is not a good situation, but not necessarily one that warrants immediate intervention - that would come when it starts dropping writes.

**Review by tustvold — APPROVED** [review]
FWIW the database name will be included by the background worker span, but can't hurt to have it twice

**Comment by alamb** [comment]
> FWIW the database name will be included by the background worker span, but can't hurt to have it twice

@tustvold  I checked [the logs](https://logs.aws.influxdata.io/messages/teamconductor_69/a43a5075-9713-11eb-834f-9edec53b730c)

And the only message that got emitted seems to be
```level=error msg="failed to find chunk to evict" span=2 target="server::db::lifecycle" location="server/src/db/lifecycle.rs:139" time=1617739617070398329
```

So in other words, I am not sure how to lookup the database name from `span=2`

**Pull request merged**
