### PR TITLE
refactor: add support for handling `TagValuesGroupedByMeasurementAndTagKeyRequest`

### PR DESCRIPTION
**Pull request by e-dard**
Towards #3372.

This PR adds some initial server and storage client plumbing to handle a `TagValuesGroupedByMeasurementAndTagKeyRequest` message.

If this message is sent over the gRPC API the server used to respond with:

```
actual  : "{\"results\":[{\"statement_id\":0,\"error\":\"rpc error: code = Unimplemented desc = \"}]}"
```

and now will respond with:

```
actual  : "{\"results\":[{\"statement_id\":0,\"error\":\"rpc error: code = Internal desc = Operation not yet implemented:  tag_values_grouped_by_measurement_and_tag_key. Measurement patterns:......
```

### CODE REVIEW

**Review by crepererum — APPROVED** [review]

**Review by alamb — APPROVED** [review]
👌

**Comment by alamb** [comment]
Semantic Pull Request 😢 

Screen Shot 2021-12-14 at 1 21 36 PM

**Comment by alamb** [comment]
(renamed PR slightly to force semantic PR to re-run)

**Comment by e-dard** [comment]
@alamb 🙇 thanks.

**Pull request merged**
