### PR TITLE
fix: Fix copy&pasted check_response descriptions

### PR DESCRIPTION
**Pull request by mkmik**
Copy pasta is best pasta

### CODE REVIEW

**Review by alamb — APPROVED** [review]
Nice and 🧹  👍

**Comment by mkmik** [comment]
I'm confused; how was this commit merged in main?

**Comment by mkmik** [comment]
ah, the other way around, it was "synced" with main

**Comment by alamb** [comment]
> ah, the other way around, it was "synced" with main

@mkmik  -- this repo is setup so that you can't merge your PR if it "out of sync" with main -- so I clicked the "update" button to do so (after I merged https://github.com/influxdata/influxdb_iox/pull/738 and this PR became unmergable).

**Comment by alamb** [comment]
The upside to the "must be against master" is that you can't get logical conflicts that result in broken tests (because the tests actually ran against the specific code in the PR). The downside is with multiple outstanding PRs you end up sometimes "racing" to see who can sync with main and merge fastest -- and if you lose the race you have to sync and try again

**Comment by mkmik** [comment]
I'm familiar with the tradeoff :-) the downside is that with non-trivial number of developers landing code and CI times in the 10m range, after a while landing something becomes a major pain.

But luckily there are bots that can do this job for us, like https://github.com/apps/bors

**Comment by alamb** [comment]
Yeah, with 6 devs it was not too painful. With our newly increased team size it may well be time for automation.

**Pull request merged**
