### PR TITLE
fix: Remove old ingester and ioxd_ingester

### PR DESCRIPTION
**Pull request by carols10cents**
Extracted from https://github.com/influxdata/influxdb_iox/pull/7049.

This commit removes the old ingester.

As https://github.com/influxdata/idpe/issues/17122 is now done, and even though I'm on vacation, I wanted to start sending in PRs for the separate commits in my big deletion PR for ease of reviewing, verifying, and merging.

### CODE REVIEW

**Review by Joe-Blount — APPROVED** [review]
LGTM

**Review by philjb — APPROVED** [review]
Ingester, you have been digested.

**Comment by alamb** [comment]
`cargo_audit` is failing for unrelated reasons -- here is a PR to fix it https://github.com/influxdata/influxdb_iox/pull/7488

**Comment by alamb** [comment]
Updated from main to pick up `cargo_audit` changes in https://github.com/influxdata/influxdb_iox/pull/7488

**Pull request merged**
