### PR TITLE
fix: reduce log verbosity for `found compaction candidates` message

### PR DESCRIPTION
**Pull request by alamb**
# Rationale

When I run iox in local mode with debug logging turned on  (`cargo run -- -vv`) the following message is printed several times a second:

```shell
2022-07-27T15:29:52.679536Z DEBUG compactor::handler: found compaction candidates n_candidates=0
2022-07-27T15:29:52.679650Z DEBUG compactor::handler: found compaction candidates n_candidates=0
2022-07-27T15:29:52.679764Z DEBUG compactor::handler: found compaction candidates n_candidates=0
2022-07-27T15:29:52.679878Z DEBUG compactor::handler: found compaction candidates n_candidates=0
2022-07-27T15:29:52.679992Z DEBUG compactor::handler: found compaction candidates n_candidates=0
2022-07-27T15:29:52.680106Z DEBUG compactor::handler: found compaction candidates n_candidates=0
2022-07-27T15:29:52.680220Z DEBUG compactor::handler: found compaction candidates n_candidates=0
2022-07-27T15:29:52.680334Z DEBUG compactor::handler: found compaction candidates n_candidates=0
2022-07-27T15:29:52.680520Z DEBUG compactor::handler: found compaction candidates n_candidates=0
2022-07-27T15:29:52.680825Z DEBUG compactor::handler: found compaction candidates n_candidates=0
2022-07-27T15:29:52.681014Z DEBUG compactor::handler: found compaction candidates n_candidates=0
2022-07-27T15:29:52.681139Z DEBUG compactor::handler: found compaction candidates n_candidates=0
2022-07-27T15:29:52.681262Z DEBUG compactor::handler: found compaction candidates n_candidates=0
2022-07-27T15:29:52.681486Z DEBUG compactor::handler: found compaction candidates n_candidates=0
2022-07-27T15:29:52.681604Z DEBUG compactor::handler: found compaction candidates n_candidates=0
2022-07-27T15:29:52.681722Z DEBUG compactor::handler: found compaction candidates n_candidates=0
2022-07-27T15:29:52.681838Z DEBUG compactor::handler: found compaction candidates n_candidates=0
2022-07-27T15:29:52.681955Z DEBUG compactor::handler: found compaction candidates n_candidates=0
2022-07-27T15:29:52.682072Z DEBUG compactor::handler: found compaction candidates n_candidates=0
2022-07-27T15:29:52.682189Z DEBUG compactor::handler: found compaction candidates n_candidates=0
2022-07-27T15:29:52.682306Z DEBUG compactor::handler: found compaction candidates n_candidates=0
2022-07-27T15:29:52.682499Z DEBUG compactor::handler: found compaction candidates n_candidates=0
2022-07-27T15:29:52.682615Z DEBUG compactor::handler: found compaction candidates n_candidates=0
2022-07-27T15:29:52.682731Z DEBUG compactor::handler: found compaction candidates n_candidates=0
2022-07-27T15:29:52.682847Z DEBUG compactor::handler: found compaction candidates n_candidates=0
```

# Changes
1. ~Turn this log to `trace!`~
2. Only print the log when there is something to do 
3. Sleep for `1 sec` if the compactor found nothing to do

### CODE REVIEW

**Comment by NGA-TRAN** [comment]
@alamb This is a very useful log for us right now. I am not sure I want to move this to trace because but won't show up in the log file

**Comment by NGA-TRAN** [comment]
Yeah, if n_candidate is 0, we do not need to print it

**Comment by alamb** [comment]
>  Yeah, if n_candidate is 0, we do not need to print it

Thanks @NGA-TRAN 

I changed it so:
1. We Only print the log when there is something to do
2. It now sleeps for 1 sec if the compactor found nothing to do (so all-in-one mode on an empty database doesn't spend a CPU core in a busy loop looking for work)

**Review by NGA-TRAN — APPROVED** [review]
Looks good. Thanks @alamb

**Pull request merged**
