### PR TITLE
refactor: accept `impl Into<String>` instead of `&str` for schema methods

### LINKED ISSUE #7764: Change methods in the `schema` crate that take `&str` parameters to take `impl Into<String>` when possible
[See this comment for context](https://github.com/influxdata/influxdb_iox/pull/7692#discussion_r1187396809).

Methods like [`schema::SchemaBuilder::influx_column`](https://github.com/influxdata/influxdb_iox/blob/dc1a9e9ed6ff45c099e828c5e083d85cc2e70c09/schema/src/builder.rs#L61) currently take `&str` arguments, then pass those (eventually) to [`arrow::datatypes::Field::new`](https://docs.rs/arrow/latest/arrow/datatypes/struct.Field.html#method.new), which takes `impl Into<String>`. 

Change our methods from `&str` to `impl Into<String>` to match the arrow methods, which would let callers decide whether they want to borrow or give up ownership.

### PR DESCRIPTION
**Pull request by kayagokalp**
Closes #7764 

Changes `schema` methods to accept `impl Into<String>` instead of `&str` so that caller can decide whether to own it or now. I am not sure if the added flexibility is worth the monomorphization hit the compile time would end up with. Considering it is only couple of methods this shouldn't matter, I wonder if it would affect if this type of changes introduced to everywhere.

- [x] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

### CODE REVIEW

**Review by alamb — APPROVED** [review]
Thank you as well for this contribution @kayagokalp  -- much appreciated.

**Review by alamb — COMMENTED** [review]
> I am not sure if the added flexibility is worth the monomorphization hit the compile time would end up with. Considering it is only couple of methods this shouldn't matter, I wonder if it would affect if this type of changes introduced to everywhere

I don't think the the monomorphism will make a big difference as there are typically at most 2 types that are passed in to this kind of method -- `&str` and `String`

**Comment by alamb** [comment]
cc @domodwyer  as well as you filed https://github.com/influxdata/influxdb_iox/issues/7764

**Review by domodwyer — APPROVED** [review]
Nice!

So the reason for this change (beyond the general "accept what you need" rule of thumb) is specifically to allow us to optimise the conversion from a `ColumnsByName` to a `Schema` instance here:

https://github.com/influxdata/influxdb_iox/blob/ac0ea99cde6625af47a6961b2614052e193c6e35/data_types/src/columns.rs#L113-L135

Because the `SchemaBuilder` used to take a `&str` it forced the owned conversion of `From<ColumnsByName>` to have to give a `&str` reference of the owned column name `String`, where it would be cloned into a `String` for use in the schema, and then throw away the original - this is silly! We're forcing an alloc and a dealloc for every column name.

By allowing the schema to be built with owned types, this `From` impl can be updated to give up ownership of the column names, preventing lots of small allocations & deallocations (a relatively painful allocation pattern) and help improve performance / minimise memory utilisation :+1:

Would you mind updating the `From` impl I've referenced? The `From<&ColumnsByName>` should be removed, and the `From<ColumnsByName>` impl should pass ownership of the column names 🚀

**Comment by domodwyer** [comment]
Nice! 👌 

I pushed two quick commits so we can get this merged:

* refactor: impl intoIterator for ColumnsByName (160628a7f)
      
      Allows the ColumnsByName to be converted into an iterator yielding owned
      column names & schema.

* perf: move column names for Schema construction (7f52959d2)
      
      When converting from a ColumnsByName into a schema::Schema instance,
      move the column names instead of cloning them.

The first (160628a7f) allows the `ColumnsByName` to be turned into an owned iterator that yields `(String, ColumnSchema)` (in addition to the existing `(&String, &ColumnSchema)` borrowed iterator). I then use this in the second commit (7f52959d2) to _move the column names_ into the Schema constructor now you've made it possible to **move ownership** 🎉 

THANK YOU for this @kayagokalp - this will be a nice performance improvement for upcoming work ❤️

**Pull request merged**
