### PR TITLE
chore: Upgrade to Rust 1.67

### PR DESCRIPTION
**Pull request by carols10cents**
Clippy learned some new tricks, as ever!

Highly recommend reviewing commit-by-commit -- I promise this is smaller than it looks!!

The biggest change is that Clippy now warns if you can use a variable within a format string but don't. Clippy also knows how to fix some errors now, and this is one of them. I used `cargo clippy --workspace --all-targets --all-features --fix` to make the changes that are the largest commit here. You should be able to check my work by cherry-picking the upgrade commit onto a new branch so that you're upgraded too, running the command yourself and committing, then cherry-picking my commit that ran the command and verifying it's a no-op then.

The rest of the commits are very small.

### CODE REVIEW

**Review by crepererum — APPROVED** [review]
The `format!()` refactoring looks a solid amount of pain, but clippy is right: it's easier to read.

Thanks for spending all this effort in keeping us up-to-date :steam_locomotive:

**Comment by carols10cents** [comment]
OK, there are a few differences in sizes of data structures, likely due to this change: https://github.com/rust-lang/rust/pull/102750/

Then there's a test failure with `iox_query/src/exec/query_tracing.rs` [in this test](https://github.com/influxdata/influxdb_iox/blob/05ca71f91f23ca9e8eef2795b0909043174a67e3/iox_query/src/exec/query_tracing.rs#L369-L471) that I have no idea why it changed.... it's saying `thread 'exec::query_tracing::tests::children_and_timestamps' panicked at 'no entry found for key', iox_query/src/exec/query_tracing.rs:429:20`. On this branch, line 429 is looking for the key `"TestExec - exec (1)"`, and it's indeed not in the spans that are printed out just before:

<details>
<summary>Printed out spans in the test output</summary>

```text
Spans: 

{
    "TestExec - child1": Span {
        name: "TestExec - child1",
        ctx: SpanContext {
            trace_id: TraceId(
                1551780504827606518964400640389040267,
            ),
            parent_span_id: Some(
                SpanId(
                    10223286254001003137,
                ),
            ),
            span_id: SpanId(
                5597172421467735520,
            ),
            links: [],
            collector: None,
            sampled: true,
        },
        start: Some(
            1970-01-01T00:00:02Z,
        ),
        end: Some(
            1970-01-01T00:00:04Z,
        ),
        status: Unknown,
        metadata: {
            "desc": String(
                "TestExec - child1: foo",
            ),
        },
        events: [],
    },
    "TestExec - child2": Span {
        name: "TestExec - child2",
        ctx: SpanContext {
            trace_id: TraceId(
                1551780504827606518964400640389040267,
            ),
            parent_span_id: Some(
                SpanId(
                    10223286254001003137,
                ),
            ),
            span_id: SpanId(
                9107812930681452001,
            ),
            links: [],
            collector: None,
            sampled: true,
        },
        start: Some(
            1970-01-01T00:00:02Z,
        ),
        end: Some(
            1970-01-01T00:00:03Z,
        ),
        status: Unknown,
        metadata: {
            "desc": String(
                "TestExec - child2: bar",
            ),
        },
        events: [],
    },
    "TestExec - child3": Span {
        name: "TestExec - child3",
        ctx: SpanContext {
            trace_id: TraceId(
                1551780504827606518964400640389040267,
            ),
            parent_span_id: Some(
                SpanId(
                    10223286254001003137,
                ),
            ),
            span_id: SpanId(
                14257505670890979905,
            ),
            links: [],
            collector: None,
            sampled: true,
        },
        start: Some(
            1970-01-01T00:00:01Z,
        ),
        end: Some(
            1970-01-01T00:00:03Z,
        ),
        status: Unknown,
        metadata: {
            "desc": String(
                "TestExec - child3: baz",
            ),
        },
        events: [],
    },
    "TestExec - child3 (1)": Span {
        name: "TestExec - child3 (1)",
        ctx: SpanContext {
            trace_id: TraceId(
                1551780504827606518964400640389040267,
            ),
            parent_span_id: Some(
                SpanId(
                    14257505670890979905,
                ),
            ),
            span_id: SpanId(
                3501947678601805904,
            ),
            links: [],
            collector: None,
            sampled: true,
        },
        start: Some(
            1970-01-01T00:00:01Z,
        ),
        end: Some(
            1970-01-01T00:00:03Z,
        ),
        status: Unknown,
        metadata: {},
        events: [],
    },
    "TestExec - child4": Span {
        name: "TestExec - child4",
        ctx: SpanContext {
            trace_id: TraceId(
                1551780504827606518964400640389040267,
            ),
            parent_span_id: Some(
                SpanId(
                    10223286254001003137,
                ),
            ),
            span_id: SpanId(
                15802622792556067222,
            ),
            links: [],
            collector: None,
            sampled: true,
        },
        start: Some(
            1970-01-01T00:00:01Z,
        ),
        end: Some(
            1970-01-01T00:00:04Z,
        ),
        status: Unknown,
        metadata: {
            "desc": String(
                "TestExec - child4: bingo",
            ),
        },
        events: [],
    },
    "TestExec - child5": Span {
        name: "TestExec - child5",
        ctx: SpanContext {
            trace_id: TraceId(
                1551780504827606518964400640389040267,
            ),
            parent_span_id: Some(
                SpanId(
                    10223286254001003137,
                ),
            ),
            span_id: SpanId(
                2375836547082971476,
            ),
            links: [],
            collector: None,
            sampled: true,
        },
        start: Some(
            1970-01-01T00:00:01Z,
        ),
        end: Some(
            1970-01-01T00:00:04Z,
        ),
        status: Unknown,
        metadata: {
            "desc": String(
                "TestExec - child5: bongo",
            ),
        },
        events: [],
    },
    "TestExec - child5 (1)": Span {
        name: "TestExec - child5 (1)",
        ctx: SpanContext {
            trace_id: TraceId(
                1551780504827606518964400640389040267,
            ),
            parent_span_id: Some(
                SpanId(
                    2375836547082971476,
                ),
            ),
            span_id: SpanId(
                16679893431870616054,
            ),
            links: [],
            collector: None,
            sampled: true,
        },
        start: Some(
            1970-01-01T00:00:01Z,
        ),
        end: Some(
            1970-01-01T00:00:02Z,
        ),
        status: Unknown,
        metadata: {},
        events: [],
    },
    "TestExec - child5 (2)": Span {
        name: "TestExec - child5 (2)",
        ctx: SpanContext {
            trace_id: TraceId(
                1551780504827606518964400640389040267,
            ),
            parent_span_id: Some(
                SpanId(
                    2375836547082971476,
                ),
            ),
            span_id: SpanId(
                9656228443553080039,
            ),
            links: [],
            collector: None,
            sampled: true,
        },
        start: Some(
            1970-01-01T00:00:02Z,
        ),
        end: Some(
            1970-01-01T00:00:03Z,
        ),
        status: Unknown,
        metadata: {},
        events: [],
    },
    "TestExec - child5 (3)": Span {
        name: "TestExec - child5 (3)",
        ctx: SpanContext {
            trace_id: TraceId(
                1551780504827606518964400640389040267,
            ),
            parent_span_id: Some(
                SpanId(
                    2375836547082971476,
                ),
            ),
            span_id: SpanId(
                14208031555169024389,
            ),
            links: [],
            collector: None,
            sampled: true,
        },
        start: Some(
            1970-01-01T00:00:01Z,
        ),
        end: Some(
            1970-01-01T00:00:04Z,
        ),
        status: Unknown,
        metadata: {},
        events: [],
    },
    "TestExec - exec": Span {
        name: "TestExec - exec",
        ctx: SpanContext {
            trace_id: TraceId(
                1551780504827606518964400640389040267,
            ),
            parent_span_id: Some(
                SpanId(
                    11802527073862045533,
                ),
            ),
            span_id: SpanId(
                10223286254001003137,
            ),
            links: [],
            collector: None,
            sampled: true,
        },
        start: Some(
            1970-01-01T00:00:01Z,
        ),
        end: Some(
            1970-01-01T00:00:04Z,
        ),
        status: Unknown,
        metadata: {
            "desc": String(
                "TestExec - exec",
            ),
        },
        events: [],
    },
}
```

</details>

@alamb do you have any insight into why a Rust upgrade might have changed what's in the query tracing? Any pointers where I should start investigating?

**Comment by alamb** [comment]
> @alamb do you have any insight into why a Rust upgrade might have changed what's in the query tracing? Any pointers where I should start investigating?

TestExec (1) may be the name of the thread or something

I suggest updating the test to look for `TestExec - exec` 

AKA

```
 "TestExec - exec": Span {
        name: "TestExec - exec",
        ctx: SpanContext {
            trace_id: TraceId(
                1551780504827606518964400640389040267,
            ),
            parent_span_id: Some(
                SpanId(
                    11802527073862045533,
                ),
            ),
            span_id: SpanId(
                10223286254001003137,
            ),
            links: [],
            collector: None,
            sampled: true,
        },
        start: Some(
            1970-01-01T00:00:01Z,
        ),
        end: Some(
            1970-01-01T00:00:04Z,
        ),
        status: Unknown,
        metadata: {
            "desc": String(
                "TestExec - exec",
            ),
        },
        events: [],
    },
```

**Comment by alamb** [comment]
`cargo clippy --fix` worked well for us in datafusion and arrow-rs when we dealt with this upgrade

**Comment by carols10cents** [comment]
> `cargo clippy --fix` worked well for us in datafusion and arrow-rs when we dealt with this upgrade

Yes I used that as stated in the PR description and in that commit :)

**Pull request merged**
