### PR TITLE
feat: add GIT hash to `--version`

### PR DESCRIPTION
**Pull request by crepererum**
```text
$influxdb_iox --version
influxdb_iox 0.1.0, revision 34dcd991d36dbaaf820478da99119c63fc38f1b3
```

### CODE REVIEW

**Review by alamb — COMMENTED** [review]
The idea is great

I would like to request an  approach that does not require a new dependency. 

For example, I wonder if you can do something like the following, which  a function that creates the version string at runtime? 

```rust

fn get_version_str() -> &'static str {
    "foobar"
}

#[derive(Debug, StructOpt)]
#[structopt(
    name = "influxdb_iox",
    version = get_version_str(),
    about = "InfluxDB IOx server and command line tools",
    long_about = r#"about"#,
)]
struct Config {
}
```
```

**Comment by crepererum** [comment]
let me check...

**Comment by alamb** [comment]
Here is a version that works with `format!`:

```rust
use structopt::StructOpt;
use once_cell::sync::OnceCell;

static INSTANCE: OnceCell<String> = OnceCell::new();

fn get_version_str() -> &'static str {
    &INSTANCE.get_or_init(|| {
        format!("Foo: {}", "bar")
    })
}

#[derive(Debug, StructOpt)]
#[structopt(
    name = "influxdb_iox",
    version = get_version_str(),
    about = "InfluxDB IOx server and command line tools",
    long_about = r#"about"#,
)]
struct Config {
}

fn main() {
    println!("Hello, world!");
}

```

**Comment by crepererum** [comment]
I was about to commit a similar solution :D

**Comment by crepererum** [comment]
done

**Review by alamb — APPROVED** [review]
❤️  -- thank you!

**Pull request merged**
