### PR TITLE
fix: Delete all write-buffer related code

### PR DESCRIPTION
**Pull request by carols10cents**
I love deleting code! This is my attempt at removing everything having to do with the write buffer that's obsolete with this morning's plan. I also pushed [a tag named write-buffer](https://github.com/influxdata/influxdb_iox/releases/tag/write-buffer) for ease of finding this code in the future if it needs to come back.

Is this too much? Like `SequencedEntry` can all go away now, right?

### CODE REVIEW

**Comment by pauldix** [comment]
I think this is premature at this point? We're going to have a write buffer at some point in the future. And the DB will likely be getting SequencedEntry (but it might not be FB). We need to get the Kafka bits wired in I think. And the HTTP API should still exist to write directly into the MB.

**Comment by carols10cents** [comment]
Ok, no problem! My thought was that we could save time not needing to update and compile parts of the code that won't be used for a while.

**Comment by carols10cents** [comment]
@pauldix I'm reopening this based on this comment of yours in chat:

paul saying yeah, write buffer is dead

Also note that the `http` code being removed in this PR is only the types that were supporting the `WriteBufferMetadataQuery` gRPC API, and this PR does NOT remove or modify the `/api/v2/write` HTTP API. I don't think I was particularly clear about that when I opened this before.

**Comment by carols10cents** [comment]
Ok so maybe hold on this because it looks like we might still need the logical clock code.

**Comment by carols10cents** [comment]
This is ready for review now!

**Review by pauldix — COMMENTED** [review]
I believe we still need the SequencedEntry as that's what should be getting written into the MUB. The `clock_value` would end up becoming the Kafka offset, which we need to track when we persist data to Parquet files. So maybe changing `clock_value` to `sequence_number` would be more approrpiate.

**Comment by carols10cents** [comment]
@pauldix Ok, the first commit should be as you saw it, it's just rebased on main. The second commit puts back `SequencedEntry` as we discussed in chat (I think). So this should be ready for a rereview!

**Review by pauldix — APPROVED** [review]

**Pull request merged**
