### PR TITLE
chore: upgrade to snafu 0.7

### PR DESCRIPTION
**Pull request by crepererum**
https://users.rust-lang.org/t/snafu-0-7-released/69766?u=shepmaster

```
What's new?
The big-ticket changes in 0.7 are:

SNAFU's context selectors now have the suffix Snafu.
Context selectors can be placed into a module.
A batteries-included Whatever type allows getting started quickly.
Shorthand formatting syntax simplifies defining error messages.
These changes are discussed later in this post. A more detailed list of changes can be found in the changelog 26.
```

### CODE REVIEW

**Comment by mkmik** [comment]
have you used https://github.com/shepmaster/snafu-upgrade-assistant ?

**Comment by crepererum** [comment]
No, because it's not mentioned in the official changelog. :shrug:

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
Given the potential for conflicts, I am going to merge this in and ask for forgiveness later if that was a problem

**Comment by mkmik** [comment]
@crepererum did you use the automated tool now? How much did you have to retouch manually?

**Comment by crepererum** [comment]
@mkmik still no automated tool because I basically had it completed when you've pointed it out. It's basically only the suffix change (context helpers now have the Snafu suffix), one single macro change regarding string-style macro arguments (also mentioned in the breaking change), and some renames from `location` to `path` so that snafu doesn't think we're talking about the error location.

**Pull request merged**
