### PR TITLE
fix: remove unused parameter `mutable_linger_seconds` from dbrules

### PR DESCRIPTION
**Pull request by alamb**
# Rationale
`mutable_linger_seconds` was marked as deprecated here https://github.com/influxdata/influxdb_iox/pull/1949

@mkmik suggested leaving it deprecated: https://github.com/influxdata/influxdb_iox/pull/1949#r667333080 initially and then removing.

Having a setting that does nothing is confusing.

Should be merged in after https://github.com/influxdata/k8s-idpe/pull/3874

# Changes
Remove `mutable_linger_seconds` entirely

### CODE REVIEW

**Comment by mkmik** [comment]
Did we remove it already from our checked in configs now? (Sorry I'm on mobile now)

**Comment by alamb** [comment]
> Did we remove it already from our checked in configs now? (Sorry I'm on mobile now)

@mkmik  there doesn't appear to be any reference to `mutable_linger_seconds` in the k8s-idpe, if that is what you are asking:

```shell
alamb@ip-192-168-0-133 k8s-idpe % find . -type 'f' | xargs grep mutable_linger_seconds | wc -l
find . -type 'f' | xargs grep mutable_linger_seconds | wc -l
       0
alamb@ip-192-168-0-133 k8s-idpe % 
```

**Comment by mkmik** [comment]
Yes I'm asking that, please search for camel case mutableLingerSeconds

**Comment by mkmik** [comment]
(I'm not saying it's there, but if it is there it uses the protobuf canonical json encoding which is camel case)

**Comment by alamb** [comment]
> Yes I'm asking that, please search for camel case mutableLingerSeconds

Right you are @mkmik 

```shell
alamb@ip-192-168-0-133 k8s-idpe % find . -type 'f' | xargs grep mutableLingerSeconds | wc -l
find . -type 'f' | xargs grep mutableLingerSeconds | wc -l
      73
```

I will create a PR to remove it

**Comment by alamb** [comment]
Remove the config setting from the internal config in https://github.com/influxdata/k8s-idpe/pull/3874

**Review by mkmik — APPROVED** [review]

**Comment by alamb** [comment]
https://github.com/influxdata/k8s-idpe/pull/3874 was merged

**Pull request merged**
