### PR TITLE
feat: Flatbuffers root_type and file_identifier

### PR DESCRIPTION
**Pull request by mkmik**
it makes it easier to work with flatbuffers tooling

### CODE REVIEW

**Review by alamb — APPROVED** [review]
looks reasonable to me

**Comment by mkmik** [comment]
I'll postpone the merge of this until next week; first I want to have stuff writing into kafka

**Comment by alamb** [comment]
@mkmik  is this something we should merge?

**Comment by mkmik** [comment]
Yes

**Pull request merged**
