### PR TITLE
feat: improve `RouterClient` errors

### PR DESCRIPTION
**Pull request by crepererum**
Found while working on conductor.

### CODE REVIEW

**Review by tustvold — APPROVED** [review]
I'm not a massive fan of wrapping each of these methods with its own error type that just exposes a subset of the variants of tonic::Status, but I guess this is the convention at the moment :shrug:

**Comment by alamb** [comment]
> I'm not a massive fan of wrapping each of these methods with its own error type that just exposes a subset of the variants of tonic::Status, but I guess this is the convention at the moment 🤷

What is the alternative @tustvold ?  Would you suggest a single `Error` type shared by all the function calls as is done elsewhere in the code?

**Comment by tustvold** [comment]
> What is the alternative @tustvold ? Would you suggest a single Error type shared by all the function calls as is done elsewhere in the code?

Possibly, or just returning the `tonic::Status`... The gRPC designers already went to the effort of defining useful error variants, and mapping them to error codes, it seems somewhat unnecessary to be building our own... It's also possible I'm just grumpy about the amount of error propagation code we have, and this is an easy target :laughing:

**Comment by alamb** [comment]
🤔  indeed

**Pull request merged**
