### PR TITLE
feat: make CLI to listing database consistent with other commands

### PR DESCRIPTION
**Pull request by alamb**
# Current behavior:

To list databases
```
influxdb_iox database get
```
(aka no args)

To list remotes:
```
influxdb_iox remote list
```

To list chunks
```
influxdb_iox database chunk list
```

# Proposed behavior:
List databases via
```
influxdb_iox db list
```

Making it consistent with the other commands

- [x] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

### CODE REVIEW

**Comment by alamb** [comment]
FYI @tustvold  and @mkmik

**Review by tustvold — COMMENTED** [review]
I was just following the example of kubectl, but if this is less confusing to people :shrug:

**Review by mkmik — APPROVED** [review]
LGTM

**Comment by alamb** [comment]
Let's go with `list` for now for consistency

**Pull request merged**
