### PR TITLE
docs: Improving Readability r2

### PR DESCRIPTION
**Pull request by ryanrussell**
Closes #

Readability improvements. Focus on `TOML` files.

- [x] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

### CODE REVIEW

**Review by alamb — APPROVED** [review]
Thanks @ryanrussell !  This PR's commit messages aren't "semanitic" (aka they don't start with `docs: ` -- any chance you can rebase the PR to reword the messages?

I am also happy to do so.

Thanks again

**Comment by ryanrussell** [comment]
> Thanks @ryanrussell ! This PR's commit messages aren't "semanitic" (aka they don't start with `docs: ` -- any chance you can rebase the PR to reword the messages?
> 
> I am also happy to do so.
> 
> Thanks again

@alamb I rebased with a reword on commit messages and `git push --force origin main`.

Hope this is what you want; if not, feel free to squash on your side.

Will use semantic on titles moving forward... any chances you guys to go to conventional commits in the future?

Best,
Ryan

**Comment by alamb** [comment]
> Will use semantic on titles moving forward... any chances you guys to go to conventional commits in the future?

yes -- i am sorry -- that is what we do https://www.conventionalcommits.org/en/v1.0.0/

**Comment by alamb** [comment]
Thanks again

**Pull request merged**
