### PR TITLE
chore: Update datafusion and sqlparser

### PR DESCRIPTION
**Pull request by alamb**
# Rationale:
Keep up with DataFusion.
Notable improvements:
* https://github.com/apache/arrow-datafusion/pull/1375 (Unified simplification)
* https://github.com/apache/arrow-datafusion/pull/1419,
* https://github.com/apache/arrow-datafusion/pull/1415

# Changes:
1. Update DataFusion pin to https://github.com/apache/arrow-datafusion/commit/b17e1b2b60618ba82818846ab079a916248b8c4f
2. Update sqlparser pin

### CODE REVIEW

**Review by tustvold — APPROVED** [review]
Approving but test failure appears to be legitimate

**Comment by alamb** [comment]
> Approving but test failure appears to be legitimate

Weird -- I swear the tests passed for me locally. Will sort it out

**Review by NGA-TRAN — APPROVED** [review]

**Comment by alamb** [comment]
The actual error in the end to end test is:

**Comment by alamb** [comment]
Rerunning with 

```
LOG_FILTER=debug cargo test -p influxdb_iox --test end_to_end -- test_read_group_count_agg
```

we can see the plan with type:

```
2021-12-13T14:38:49.773630Z DEBUG query::exec::context: prepare_plan: initial plan text=Projection: #cpu.cpu, #cpu.host, CAST(#usage_system AS Int64) AS usage_system, CAST(#usage_user AS Int64) AS usage_user, #time [cpu:Dictionary(Int32, Utf8);N, host:Dictionary(Int32, Utf8);N, usage_system:Int64;N, usage_user:Int64;N, time:Timestamp(Nanosecond, None);N]
  Sort: #cpu.cpu ASC NULLS FIRST, #cpu.host ASC NULLS FIRST [cpu:Dictionary(Int32, Utf8);N, host:Dictionary(Int32, Utf8);N, usage_system:UInt64;N, usage_user:UInt64;N, time:Timestamp(Nanosecond, None);N]
    Projection: #cpu.cpu, #cpu.host, #usage_system, #usage_user, #time [cpu:Dictionary(Int32, Utf8);N, host:Dictionary(Int32, Utf8);N, usage_system:UInt64;N, usage_user:UInt64;N, time:Timestamp(Nanosecond, None);N]
      Aggregate: groupBy=[[#cpu.cpu, #cpu.host]], aggr=[[COUNT(#cpu.usage_system AS usage_system) AS usage_system, COUNT(#cpu.usage_user AS usage_user) AS usage_user, MAX(#cpu.time) AS time]] [cpu:Dictionary(Int32, Utf8);N, host:Dictionary(Int32, Utf8);N, usage_system:UInt64;N, usage_user:UInt64;N, time:Timestamp(Nanosecond, None);N]
        Filter: TimestampNanosecond(0) <= #cpu.time AND #cpu.time < TimestampNanosecond(2001) [cpu:Dictionary(Int32, Utf8);N, host:Dictionary(Int32, Utf8);N, time:Timestamp(Nanosecond, None), usage_system:Float64;N, usage_user:Float64;N]
          TableScan: cpu projection=None [cpu:Dictionary(Int32, Utf8);N, host:Dictionary(Int32, Utf8);N, time:Timestamp(Nanosecond, None), usage_system:Float64;N, usage_user:Float64;N]
```

**Comment by alamb** [comment]
I did some bisecting, and it turns the IOx tests starts failing at datafusion after commit https://github.com/apache/arrow-datafusion/pull/1378 (not my initial guess)

```
(FAILED) 591932fc9a67df714db281e2cdd3f2090323fa82 Support sort on unprojected columns (#1415) 
(FAILED) c92d5db8f6277a4a56422f6d9cdff2bc5b2a704f Metadata is kept in projections for non-derived columns
(PASSED) 8295412848bc7b5f2ce76377e8e70bbadecb551a: Make FLOAT SQL type map to Float32 rather than Float64 (#1423)
```

Looking into that more carefully

**Comment by alamb** [comment]
Filed https://github.com/apache/arrow-datafusion/issues/1447 for the underlying datafusion issue.

**Comment by alamb** [comment]
And here is the PR to fix the issue: https://github.com/apache/arrow-datafusion/pull/1448

**Comment by alamb** [comment]
Closing this one and will make a new one with fixes

**Comment by alamb** [comment]
Try 2: https://github.com/influxdata/influxdb_iox/pull/3359

**Pull request closed without merging**
