### PR TITLE
docs: fix the wrong link jumping in README

### PR DESCRIPTION
**Pull request by LLThomas**
Solve the link jumping problem.
- [x] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

### CODE REVIEW

**Review by alamb — APPROVED** [review]
Thanks @LLThomas !

I tried it out on https://github.com/LLThomas/influxdb_iox#compiling-and-running and it worked great 👍

**Comment by alamb** [comment]
Hi @LLThomas  -- thank you. Could you please submit a CLA https://influxdata.com/community/cla/ ? I couldn't find a record of your having submitted one.

Thank you!
Andrew

**Comment by LLThomas** [comment]
> Hi @LLThomas -- thank you. Could you please submit a CLA https://influxdata.com/community/cla/ ? I couldn't find a record of your having submitted one.
> 
> Thank you! Andrew

Hi Andrew, I have submitted one.

**Comment by alamb** [comment]
> Hi Andrew, I have submitted one.

I see it -- thank you @LLThomas !

**Pull request merged**
