### PR TITLE
refactor: Go from 4 `server`s to 2

### PR DESCRIPTION
**Pull request by carols10cents**
I've been getting confused by all the files with `server` in their names 😰

This renames `commands/server` to `commands/influxdb_ioxd` and moves the code in `server/src/server.rs` to `server/src/lib.rs`.

This also extracts the panic logging into its own crate, which will set up moving `src/server/` into `server/`, but I know there's active work going on in that area so I didn't want to mess with that right this second.

### CODE REVIEW

**Review by domodwyer — APPROVED** [review]
My sanity salutes you 🎉

**Review by pauldix — APPROVED** [review]
This looks good to me. Want @alamb to have a quick look as well

**Review by alamb — APPROVED** [review]
@carols10cents  --  Thank you -- I apologize for so many servers 👍 

image


> src/server/ into server

@carols10cents  one thing I would like to avoid if possible is moving the code in `src/server` into the `server` crate. what is in `src/server` has the http and gRPC endpoints, both of which bring a big old pile of dependencies with them which I would prefer not to have in the server crate (it already takes long enough to compile that crate -- and I have taken to doing `cargo test -p server` when testing)

How about renaming `src/server` to `src/commands/inflludb_iodx/api` instead

**Comment by carols10cents** [comment]
> How about renaming src/server to src/commands/influxdb_iodx/api instead?

Sure, I'm fine with that, if that's what makes the most sense to you all!

**Pull request merged**
