### PR TITLE
refactor:  remove the write_buffer crate dependency from ioxd_querier

### PR DESCRIPTION
**Pull request by stormasm**
Currently ioxd_querier has a dependency on the write_buffer crate...

However, the only reason the dependency exists is because (I believe) there are some old error messages in the code base that are no longer being used.

Once I removed the old error messages I was also able to remove the write_buffer crate dependency...

[Original Error Messages came from this PR](https://github.com/influxdata/influxdb_iox/commit/127467b5c4154181a508b6a50400b98a255c0409)

Please confirm these error messages are no longer being used but I don't see any reference to them in the codebase and everything appears to be working / tests pass etc..  

I am assuming that with Error messages the system / compiler will not tell you when Error messages are stale...  I believe therefore there may be other examples of Error messages in the codebase that are not being used...

I stumbled across this set when reviewing what crates depend on the write_buffer.

Closes #

Describe your proposed changes here.

- [x] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

### CODE REVIEW

**Review by crepererum — APPROVED** [review]
You're correct, this code is just a leftover of some intermediate version we had for the shard handling. Thank you! :slightly_smiling_face:

**Comment by crepererum** [comment]
Could you please adjust the commit message? Should probably `refactor: remove the write_buffer crate dependency from ioxd_querier` (i.e. add an `refactor: ` prefix).

**Review by crepererum — CHANGES_REQUESTED** [review]
Needs commit message fix.

**Comment by stormasm** [comment]
@crepererum thanks for your comments !

I went ahead and updated my most recent commit message with the corrected title adding in the refactor: prefix as recommended...

Hopefully that looks correct...

If not OK, please let me know...

**Comment by crepererum** [comment]
@stormasm could you please squash all our commits into a single one (w/ the fixed commit message)?

**Comment by stormasm** [comment]
@crepererum ok no problem, let me download github desktop as this appears the most simple solution to get this squashing job done --- and should be helpful for me for future commits for squashing / rebasing...

stay tuned --- I am in the process of getting this installed 😄

**Comment by stormasm** [comment]
We can close this PR and land this PR instead...

https://github.com/influxdata/influxdb_iox/pull/5563

**Comment by crepererum** [comment]
Closed by #5563.

**Pull request closed without merging**
