### PR TITLE
chore: Run end to end integration tests as part of a separate circle CI Job

### PR DESCRIPTION
**Pull request by alamb**
# Rationale:

As part of making end to end integration tests easier to run locally (https://github.com/influxdata/influxdb_iox/issues/7285) I want to ensure:

1. The file based sqllite catalog passes all tests (so developers can rely on it)
2. The posgres based catalog also passes all tests

Thus I propose running tests in CI both with and without postgres available (see  https://github.com/influxdata/influxdb_iox/pull/7657)

# Changes
1. Run `cargo test --workspace` without any external dependencies
2  Run targeted `cargo_test` with that require external dependencies
3. Combine the JDBC test into 2.

I also checked and the timings are about the same (the new integration test takes about as long as the exising main test)

# Changes needed for this PR
After this PR, someone will need to change the configuration of the influxdb_iox repository to:
- [x] No longer require the `test-flight-sql-jdbc` job
- [x] Require the new `test_integration` job

### CODE REVIEW

**Comment by crepererum** [comment]
This needs a repo admin to adjust our "required" config:

image


image

(i.e. remove one, add one)

**Review by crepererum — APPROVED** [review]

**Comment by philjb** [comment]
yikes! I assume postgres and sqlite were both run in ci.

**Comment by crepererum** [comment]
> yikes! I assumed postgres and sqlite were both run in ci.

they are, but just for the `iox_catalog` crate. i.e. we test that particular interface w/ all "backend" impls but do NOT run a full end2end test. we did the same for the old "write buffer" crate and for the object store interaction as well.

**Comment by carols10cents** [comment]
@alamb I have [a PR that includes a migration for both postgres and sqlite](https://github.com/influxdata/influxdb_iox/pull/7605), and that I have rebased on main to include this. The tests are failing as if the migrations haven't been run but I don't see how??? Do you have any ideas?

**Comment by carols10cents** [comment]
Nevermind, this can't be the problem because I can reproduce the failures locally 🤦🏻‍♀️

**Comment by carols10cents** [comment]
Oh yeah this is entirely my own fault, sorry for the ping!

**Comment by alamb** [comment]
>  Oh yeah this is entirely my own fault, sorry for the ping!


No worries !

**Pull request merged**
