### PR TITLE
feat: Add more logging in particular situations to debug flaky test

### PR DESCRIPTION
**Pull request by carols10cents**
I still don't know what's causing #4395. 

The debug logs didn't include all the information I was wondering about, like what the ingesters think they have, what they're sending to the querier, when they're persisting what, what the querier gets from the ingesters, what the querier sees in the catalog, what happens when the querier puts together data from the ingester and from the catalog.

### CODE REVIEW

**Comment by carols10cents** [comment]
Ok, I got lucky with the test failing on this PR, but I still don't understand how this is possible. Here are the interesting parts from the logs:

```
Test steps
==========

2022-05-16T19:39:16.673860Z  INFO test_helpers_end_to_end::client: combining response: [
    GetWriteInfoResponse {
        kafka_partition_infos: [
            KafkaPartitionInfo {
                kafka_partition_id: 0,
                status: Unknown,
            },
            KafkaPartitionInfo {
                kafka_partition_id: 1,
                status: Readable,
            },
        ],
    },
    GetWriteInfoResponse {
        kafka_partition_infos: [
            KafkaPartitionInfo {
                kafka_partition_id: 0,
                status: Readable,
            },
            KafkaPartitionInfo {
                kafka_partition_id: 1,
                status: Unknown,
            },
        ],
    },
]
All data is readable: GetWriteInfoResponse { kafka_partition_infos: [KafkaPartitionInfo { kafka_partition_id: 0, status: Readable }, KafkaPartitionInfo { kafka_partition_id: 1, status: Readable }] }
2022-05-16T19:39:16.673979Z  INFO test_helpers_end_to_end::steps: ====Begin running query: select * from table_5
thread 'end_to_end_cases::querier::multi_ingester::basic_multi_ingesters' panicked at 'assertion failed: `(left == right)`
  left: `["+------+------+--------------------------------+-----+", "| tag1 | tag2 | time                           | val |", "+------+------+--------------------------------+-----+", "|
A    | B    | 1970-01-01T00:00:00.000123456Z | 5   |", "+------+------+--------------------------------+-----+"]`,
 right: `["++", "++"]`:


Querier
========

2022-05-16T19:39:16.731785Z DEBUG querier::ingester::flight_client: Sending request to ingester ingester_addr=http://127.0.0.1:8094 request=IngesterQueryRequest { namespace: "168750582350
9076_8178011575095069", table: "table_5", columns: ["tag1", "tag2", "time", "val"], predicate: Some(Predicate { field_columns: None, partition_key: None, range: None, exprs: [], value_exp
r: [] }) }
2022-05-16T19:39:16.733150Z DEBUG querier::ingester::flight_client: Sending request to ingester ingester_addr=http://127.0.0.1:8093 request=IngesterQueryRequest { namespace: "168750582350
9076_8178011575095069", table: "table_5", columns: ["tag1", "tag2", "time", "val"], predicate: Some(Predicate { field_columns: None, partition_key: None, range: None, exprs: [], value_exp
r: [] }) }
2022-05-16T19:39:16.735780Z DEBUG querier::ingester: Ingester does not know namespace or table, skipping ingester_address=http://127.0.0.1:8094 namespace_name=1687505823509076_81780115750
95069 table_name=table_5
2022-05-16T19:39:16.737107Z DEBUG querier::ingester: Ingester does not know namespace or table, skipping ingester_address=http://127.0.0.1:8093 namespace_name=1687505823509076_81780115750
95069 table_name=table_5
2022-05-16T19:39:16.737206Z DEBUG querier::table: Ingester partitions fetched namespace=1687505823509076_8178011575095069 table_name=table_5 num_ingester_partitions=0
2022-05-16T19:39:16.739251Z DEBUG querier::table: Parquet files from catalog parquet_files=[] namespace=1687505823509076_8178011575095069 table_name=table_5
2022-05-16T19:39:16.740447Z DEBUG querier::table: Parquet files after filtering parquet_files=[] namespace=1687505823509076_8178011575095069 table_name=table_5
2022-05-16T19:39:16.740510Z DEBUG querier::table: Querier chunks num_chunks=0


Ingester 8093, kafka_partition=0
================================

2022-05-16T19:39:16.735172Z DEBUG ingester::querier_handler: prepare_data_to_querier request=IngesterQueryRequest { namespace: "1687505823509076_8178011575095069", table: "table_5", colum
ns: ["tag1", "tag2", "time", "val"], predicate: Some(Predicate { field_columns: None, partition_key: None, range: None, exprs: [], value_expr: [] }) }
2022-05-16T19:39:16.735328Z  INFO ingester::server::grpc: err=TableNotFound { namespace_name: "1687505823509076_8178011575095069", table_name: "table_5" } msg="Error handling Flight gRPC
request"


Ingester 8094, kafka_partition=1
================================
2022-05-16T19:39:16.733753Z DEBUG ingester::querier_handler: prepare_data_to_querier request=IngesterQueryRequest { namespace: "1687505823509076_8178011575095069", table: "table_5", colum
ns: ["tag1", "tag2", "time", "val"], predicate: Some(Predicate { field_columns: None, partition_key: None, range: None, exprs: [], value_expr: [] }) }
2022-05-16T19:39:16.733896Z  INFO ingester::server::grpc: err=TableNotFound { namespace_name: "1687505823509076_8178011575095069", table_name: "table_5" } msg="Error handling Flight gRPC
request"
```

So how could the ingesters say the data is readable, but then say the table isn't found, and there aren't any parquet files?

**Comment by alamb** [comment]
> So how could the ingesters say the data is readable, but then say the table isn't found, and there aren't any parquet files?

Sounds like it is the timing gap we (e.g. @crepererum  and I) were worried about where the ingester persists data between the time the querier looks at the catalog and when it gets the data from the ingester.


```
                                       3. Querier                   
   │   1. Ingester tells               retrieves the                
       to Querier about                parquet files                
   │   the data it knows               Ingester told it             
       about                           about                        
   │                                                                
                                                                    
───┼──────────────────────────▲───────────────────────▶  Time       
                              │                                     
   │                                                                
                              │                                     
                                                                    
                              │                                     
                      2. Ingester                                   
                      persists the data                             
                      into a parquet                                
                      file, and removes                             
                      it from memory                                
                                                                    
```


The design is that the ingester reports to  the querier about the last persisted file and the querier uses that to determine if it is missing parquet files that the ingester knew about. 

I wonder if the issue is that the ingester is returning an error (404 / unknown table) rather than information about the last persisted file and thus the querier incorrectly assumes the ingester had never persisted a parquet file for that table

Here are the fields the querier is supposed to be looking at
https://github.com/influxdata/influxdb_iox/blob/cn%2Fclearer-logging/querier/src/ingester/mod.rs#L419-L421

**Review by alamb — APPROVED** [review]
👍

**Comment by carols10cents** [comment]
> I wonder if the issue is that the ingester is returning an error (404 / unknown table) rather than information about the last persisted file and thus the querier incorrectly assumes the ingester had never persisted a parquet file for that table

Ok, good, that's what I was starting to suspect too; I added some more debugs in ingester/src/querier_handler.rs that maybe should catch that case. Merging to see if we can get one! 🎣

**Comment by crepererum** [comment]
After talking to @alamb here are some comments / clarifications:

- the querier catalog/ingester interaction is:
  1. querier asks catalog for schemas/tables (or uses a cached version)
  2. querier asks ingester
  3. querier asks catalog for parquet file and tombstones (this is currently NOT cached)

- if the ingester doesn't have any unpersisted data for a table, it probably answers w/ "table not found", see
  
  https://github.com/influxdata/influxdb_iox/blob/87d8a8b6848a85e50cec9816f071158f801c930f/ingester/src/querier_handler.rs#L155-L161
  
  The querier explicitly handles that case, see
  
  https://github.com/influxdata/influxdb_iox/blob/87d8a8b6848a85e50cec9816f071158f801c930f/querier/src/ingester/mod.rs#L241-L248

  So the `Ingester does not know namespace or table, skipping...` is OK.

- what's fishy is the `Parquet files from catalog parquet_files=[] ` line. The ingester just persisted the data and the catalog request is not cached (see first note), so why is the parquet file not present?

**Pull request merged**
