### PR TITLE
feat(iox/compactor/simulator): include max_l0_created_at in parquet file info printed

### PR DESCRIPTION
**Pull request by Joe-Blount**
The first commit modifies the simulator to display the max_l0_created_at time for each file.  The simulator uses a mocked time provider, which is initialized to 0.  So all timestamps are 0 + whatever the test case adds.  Most add a few nanoseconds, a few tests add minutes.  This allows the time to be displayed as `ns`, `us`, `ms`, or `s`, representing nanoseconds, microseconds, milliseconds, or seconds, respectively.  

I suggest looking at the first commit, and skimming the second commit.
The first commit is the small functional change to the simulator.
The second commit is accepting all the insta updates.

- [x] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

### CODE REVIEW

**Review by alamb — APPROVED** [review]
The code looks good to me 👍 Thanks @Joe-Blount 

Some suggestions: 
1. Update the docs here with interpretation of the max l0 time
https://github.com/influxdata/influxdb_iox/blob/5b359c3e30e6c8031d4ceffb884660d430f97ad7/compactor2_test_utils/src/display.rs#L132-L145

Possibly consider updating the width of the test output. The l0 times take up ~5 more characters which squeezes the width of the remaining times into that much less width

Maybe it would be valuable to increase the widths by 5 (or even 10) here

https://github.com/influxdata/influxdb_iox/blob/5b359c3e30e6c8031d4ceffb884660d430f97ad7/compactor2_test_utils/src/display.rs#L86-L90

**Comment by alamb** [comment]
I think https://circleci.com/gh/influxdata/influxdb_iox/277520 is failing because of the unit tests for display

I hit the same things before too (forgetting to run tests in the `compactor2_test_utils` crate). Maybe we should move those tests into the compactor/test as well for better developer experience 🤔

**Comment by alamb** [comment]
> I think the question is, how to test/verify that data is deduplicated correctly. max_l0_created_at is definitely not enough, it needs to go with non-overlapped L1 & L2 but so far no clear algorithm to do so. We have gone through a lot of drawings, tests and discussion for this while building compactor1.

I don't understand what this means -- is it documented anywhere? I tried to capture the related invariant in https://docs.google.com/presentation/d/19vzrQTrt8wv_zBG56VcrCSLlf55r285mCc5OtVeUQN0/edit#slide=id.g1f97e2604cd_1_3 but I am not sure I got it

**Comment by NGA-TRAN** [comment]
@alamb : 
This is the invariant we want
https://github.com/influxdata/idpe/issues/17258#issuecomment-1464380736

**Pull request merged**
