### PR TITLE
refactor: Change catalog configuration so it is entirely dsn based / support end to end testing without postgres

### PR DESCRIPTION
**Pull request by alamb**
~Draft as it builds on https://github.com/influxdata/influxdb_iox/pull/7735~

Closes https://github.com/influxdata/influxdb_iox/issues/7285

# Rationale

I would like to make it easier to run run end to end tests (see https://github.com/influxdata/influxdb_iox/issues/7285) and thus permitting the end to end tests to run with sqlite is good

This time, let't not break the catalog!

# Note

The first try of this feature in https://github.com/influxdata/influxdb_iox/pull/7708 caused issues on productions as it did not handle `dsn-file://` urls -- and was backed out in https://github.com/influxdata/influxdb_iox/pull/7714 (thanks @domodwyer). This PR properly handles `dsn-file://` urls and passes the tests added in https://github.com/influxdata/influxdb_iox/pull/7735 

# Changes:
1. Update the catalog configuration to be entirely based on the `INFLUXDB_IOX_CATALOG_DSN` rather than DSN and `INFLUXDB_IOX_CATALOG_TYPE`.
2. Remove `INFLUXDB_IOX_CATALOG_TYPE`

So the DSN can now be one of:
1. postgres (unchanged)
3. `memory` (memory)
4. `sqlite://<filename>`
5. `dsn-file://<filename>` (NEW since https://github.com/influxdata/influxdb_iox/pull/7735 )

For end to end testing, it can also be `sqlite` which will result in using a temporary file

Note this does not yet enable the sqlite based catalogs by default in end to end testing (or CI). That is tracked by https://github.com/influxdata/influxdb_iox/issues/7709

# Example Use
Now you can run end to end tests like this (without postgres) and it works great most of the time:

```sql
TEST_INTEGRATION=1 TEST_INFLUXDB_IOX_CATALOG_DSN=sqlite cargo test --test end_to_end 
```

### CODE REVIEW

**Review by carols10cents — APPROVED** [review]
This LGTM but I'm scared... is this a good friday afternoon change because if it breaks prod, it won't affect too many people and we can roll it back quick, or is this better for a monday morning change? Up to you, @alamb !

**Comment by alamb** [comment]
> This LGTM but I'm scared... is this a good friday afternoon change because if it breaks prod, it won't affect too many people and we can roll it back quick, or is this better for a monday morning change? Up to you, @alamb !

Thank you for the review @carols10cents  -- I  agree -- definitely let's not merge this until next week at the earliest (given many people will be traveling for the engineering offsite, I think I will will wait until I get an OK from whoever is around/on call).

**Comment by alamb** [comment]
Update here is I plan to merge this PR tomorrow when I am around and standing by to roll it back if any issues crop up

**Comment by alamb** [comment]
I plan to merge this PR later today. Status / plan in slack: https://influxdata.slack.com/archives/C04K1QRSDFG/p1684322095510709

**Comment by alamb** [comment]
Revert PR is prepared in case this PR causes issues: https://github.com/influxdata/influxdb_iox/pull/7814

**Pull request merged**
