### PR TITLE
feat: enable ZSTD compression for write buffer payload 

### LINKED ISSUE #5981: Enable write buffer ZSTD compression
Enable ZSTD compression for the write buffer.

While doing so, please disable the rskafka `snappy` feature since this is unused and all other cluster no longer have snappy-compressed data in them.

### PR DESCRIPTION
**Pull request by crepererum**
Closes #5981.

### CODE REVIEW

**Review by cannonpalms — APPROVED** [review]

**Comment by cannonpalms** [comment]
I don't think this actually enabled compression. We saw zero change in CPU usage in routers/ingesters, which presumably should be spending some amount of time compressing/decompressing data. We also saw zero change in network flow into/out of kafka. Now, it is possible that the compression ratio is literally 0%, but highly unlikely.

Could something be missing here?

**Comment by cannonpalms** [comment]
https://github.com/influxdata/influxdb_iox/commit/99b358d4818774fb6d8c3f10afaff3db533a8b31#diff-73f0baeb2ae102aaf6ffa910c45d31a1bdcd78c5d498e2bf55660d16a2bd41aaR99

Have things been refactored such that this is no longer required?

**Comment by cannonpalms** [comment]
OK, I confirmed by looking at the data within kafka itself--this PR did not actually enable compression.

**Comment by cannonpalms** [comment]
```
[kafka@iox-kafka-0 kafka]$ ./bin/kafka-console-consumer.sh  --topic iox-shared --bootstrap-server iox-kafka-bootstrap:9092 --partition 32 --max-messages 1

�
!fbe418727d3a2d93_7a09333feab33aa7�
api_call)
organisation_id▒B


3288"+

environment▒B


Production
"▒
time▒

��������"(
resource▒B


identities
"#
project▒B


Sendit"+
host▒B

api.flagsmith.com"$

project_id▒B


3813"6

organisation▒!B
▒
3288-Fullsenders Inc"
request_count▒
"(
environment_id▒B


9190"▒▒
2022-11-01
Processed a total of 1 messages
```

**Comment by crepererum** [comment]
> OK, I confirmed by looking at the data within kafka itself--this PR did not actually enable compression.

How does your console output below confirm that hypothesis? The CLI interface always emits uncompressed data.

**Pull request merged**
