### PR TITLE
feat: Add jemalloc stats

### PR DESCRIPTION
**Pull request by mkmik**
not sure how to define the metric. independent metrics, big metric with tags like these?

should the metric be jemalloc specific (after all, most of these facets are jemalloc specific)

### CODE REVIEW

**Comment by crepererum** [comment]
I would go for `jemalloc_bytes` and tag the type. That way they are:

- precisely named (they are jemalloc-specific)
- grouped together by tag

**Comment by mkmik** [comment]
> * grouped together by tag

@crepererum what do you mean grouped by tag?

**Comment by mkmik** [comment]
```
# HELP jemalloc_memstats_bytes jemalloc memstats
# TYPE jemalloc_memstats_bytes gauge
jemalloc_memstats_bytes{stat="active"} 4634976
jemalloc_memstats_bytes{stat="alloc"} 4634976
jemalloc_memstats_bytes{stat="mapped"} 66060288
jemalloc_memstats_bytes{stat="metadata"} 5954720
jemalloc_memstats_bytes{stat="resident"} 10285056
jemalloc_memstats_bytes{stat="retained"} 0
``` 
>

**Review by crepererum — APPROVED** [review]
That's what I've meant :+1:

**Pull request merged**
