### PR TITLE
feat: simplified mutable buffer configuration (RFC)

### PR DESCRIPTION
**Pull request by tustvold**
The current mutable buffer configuration appears to predate chunks, or at least has unclear semantics with respect to them. 

This PR therefore changes the configuration to something simpler in the interests of getting data flowing. I'm not saying it's perfect, nor that it is as configurable as we might like, but I think it could possibly be polished into an adequate MVP

### CODE REVIEW

**Review by pauldix — COMMENTED** [review]
The partition drop rules are still very applicable. They let the user specify which partitions to drop from the mutable buffer to free up space. When users think of dropping data, they do so by partitions, not chunks.

Closing chunks shouldn't be based strictly on the time since last write. If you have a partition for the current hour and it has a single chunk that is open, it should remain open for the entirety of that hour unless it passes the size limit.

The chunk linger value should probably be in seconds, not ms. I would expect chunks to remain open for minutes at the very least.

**Comment by tustvold** [comment]
So my, potentially incorrect, understanding was that:

* A chunk in the MUB can't be modified after it has started being moved to the REB
* There is no reason to retain chunks in the MUB once they are in the REB
* The REB representation of a chunk is smaller than the corresponding representation in the MUB
* The system should move chunks to the REB from the MUB before dropping data from the MUB

This led to the question of when would it make sense to drop partitions from the MUB without moving them first to the REB, I couldn't think of a non-exceptional situation where this would be the desired behaviour? If it did this, when would it decide to rehydrate this data? It just seemed like a lot of complexity we didn't need for an MVP?

Perhaps these drop rules would make more sense as part of the REB configuration?

> Closing chunks shouldn't be based strictly on the time since last write. If you have a partition for the current hour and it has a single chunk that is open, it should remain open for the entirety of that hour unless it passes the size limit.

When should they be closed then?

**Comment by alamb** [comment]
It is my opinion that we should stop thinking about "mutuable buffer" and "read buffer" policies and start thinking about "chunk" policies

Maybe if we reframed "partition drop rules for mutable buffer" as "partition chunk movement rules" that would help

I am thinking we need a way to control the following behaviors:
1. Moving a chunk from mutable buffer -> read buffer 
2. Persisting a chunk to parquet
3. Dropping (as in removing from the system permanently) chunks

**Comment by pauldix** [comment]
I guess the MB and RB can be thought of as a single in memory database. So in that light it would make sense to have partition drop rules for that in memory database. For example, I have data partitioned by hour and I want to drop the oldest hour partition to maintain some sort of steady-state memory footprint as I continuously write new data in (whatever now hour is).

The user doesn't think in terms of chunks, but in terms of partitions. Chunks are the database's underlying mechanism to deal with optimizing data movement from MB to RB or to deal with partitions that were cold that have suddenly started receiving writes (this is generally an edge case).

**Comment by NGA-TRAN** [comment]
My high level comments:
 1. Is it possible to do the clean-up in a separate PR or is it a must to do it with the new config?
 2. I agree with Andrew that the moving chunks from MB to RB (and then drop chunks from MB automatically) can be done  without the needs to think about dropping partitions (and all of their chunks in Mb & RB) and persisting them to parquet files.

**Comment by tustvold** [comment]
@NGA-TRAN @pauldix @alamb 

Thank you all for your feedback. I think I'll create a new PR just adding the new stuff and leaving the drop rules alone - I thought it was clearer to remove what is dead or, more accurately, not-yet alive code but it can always be done later if necessary. :+1:

**Pull request closed without merging**
