### PR TITLE
chore: remove more unused dependencies

### PR DESCRIPTION
**Pull request by alamb**
# Rationale
Inspired by @tustvold's comment on https://github.com/influxdata/influxdb_iox/pull/1652, I figured I would try and remove even more dependencies from the main development flow of recompile `influxdb_iox`

I am trying to unravel the dependency knot a little at a time

# Changes

1. Remove dependencies from the dev-build
2. Move benchmarks from influxdb_iox and mutable_buffer into `server_benchmarks` so that their dependencies can be removed from the dev build of influxdb_iox

Found via
```
cargo +nightly  udeps
```

### CODE REVIEW

**Review by tustvold — APPROVED** [review]
I'd actually meant to push the benchmarks into the crates they are for, not split them all out into a separate crate. Having to compile the server crate to compile a MUB benchmark feels a tad unfortunate, it was why I moved them under the mutable_buffer crate in the first place...

I dunno, I'd have thought the criterion and flate2 dependencies would be pretty lightweight in the grand scheme of things, but don't feel very strongly

**Comment by alamb** [comment]
Yeah, I am trying to figure out how to reduce the 517 libraries that `influxdb_iox` depends on... 😢

**Comment by alamb** [comment]
> criterion and flate2 dependencies would be pretty lightweight 

Maybe, though criterion seems quite substantial:

https://crates.io/crates/criterion/0.3.4/dependencies

**Review by e-dard — APPROVED** [review]

**Comment by alamb** [comment]
Well, I guess we can merge this and keep working on it (I'll keep messing with the code when I am waiting for something to compile :) )

**Pull request merged**
