### PR TITLE
Join me on this debugging adventure :)

### PR DESCRIPTION
**Pull request by carols10cents**
Reproducer for #6515 and verification that it's not a problem once the data gets to parquet.

The added test `boolean_parquet` passes; `boolean_ingester` fails-- so this is only a problem when the data is in the ingester's buffer.

My current status is that somewhere between the querier and the test something is getting messed up. I can confirm that: 

- the ingester's buffer has the correct data
- the ingester sends the correct data to the querier
- the querier receives the correct data
- the querier appears to send the correct data
- the test receives incorrect data

To reproduce, run:

```
RUST_LOG=info TEST_INTEGRATION=1 cargo test -p influxdb_iox boolean_ingester ; notify
```

In the test failure output, you'll first see the test logs and then each server logs. Here's the highlights with annotations of what I see in everything that gets printed out:

<details>
<summary>Logs</summary>

```
failures:

---- end_to_end_cases::querier::kafkaless_rpc_write::boolean_ingester stdout ----
(startup logs)
(test output starts)
2023-01-05T22:04:43.172705Z  INFO test_helpers_end_to_end::steps: **** Begin step 0 *****
2023-01-05T22:04:43.172717Z  INFO test_helpers_end_to_end::steps: ====Begin writing line protocol to v2 HTTP API:
the_table val=t 123456
the_table val=f 123457
2023-01-05T22:04:43.216391Z  INFO test_helpers_end_to_end::steps: ====Done writing line protocol, got token e30=
2023-01-05T22:04:43.216414Z  INFO test_helpers_end_to_end::steps: **** Begin step 1 *****
2023-01-05T22:04:43.216426Z  INFO test_helpers_end_to_end::steps: ====Begin running SQL query: select * from the_table
[iox_arrow_flight/src/client.rs:358] flight_data_to_arrow_batch(&data, Arc::clone(&state.schema),
    &state.dictionaries_by_field) = Ok(
    RecordBatch {
        schema: ...
        columns: [
            PrimitiveArray<Timestamp(Nanosecond, None)>
            [
              1970-01-01T00:00:00.000123456, (<---- timestamp ending in 6 is true)
            ],
            BooleanArray
            [
              true, (<---- this is correct)
            ],
        ],
        row_count: 1,
    },
)
[iox_arrow_flight/src/client.rs:358] flight_data_to_arrow_batch(&data, Arc::clone(&state.schema),
    &state.dictionaries_by_field) = Ok(
    RecordBatch {
        schema: ...
        columns: [
            PrimitiveArray<Timestamp(Nanosecond, None)>
            [
              1970-01-01T00:00:00.000123457, (<---- timestamp ending in 7 should be false)
            ],
            BooleanArray
            [
              true, (<---- this is INcorrect)
            ],
        ],
        row_count: 1,
    },
)
thread 'end_to_end_cases::querier::kafkaless_rpc_write::boolean_ingester' panicked at 'assertion failed: `(left == right)`
expected:

[
    "+--------------------------------+-------+",
    "| time                           | val   |",
    "+--------------------------------+-------+",
    "| 1970-01-01T00:00:00.000123456Z | true  |",
    "| 1970-01-01T00:00:00.000123457Z | false |",
    "+--------------------------------+-------+",
]
actual:

[
    "+--------------------------------+------+",
    "| time                           | val  |",
    "+--------------------------------+------+",
    "| 1970-01-01T00:00:00.000123456Z | true |",
    "| 1970-01-01T00:00:00.000123457Z | true |",
    "+--------------------------------+------+",
]

', /Users/carolnichols/rust/influxdb_iox/test_helpers_end_to_end/src/steps.rs:254:21
(test output ends)

(server logs start)
2023-01-05T22:04:43.276147Z  INFO test_helpers_end_to_end: ****************
2023-01-05T22:04:43.276154Z  INFO test_helpers_end_to_end: Start Router2 Output
2023-01-05T22:04:43.276160Z  INFO test_helpers_end_to_end: ****************
(nothing interesting in the router logs)
2023-01-05T22:04:43.276175Z  INFO test_helpers_end_to_end: ****************
2023-01-05T22:04:43.276180Z  INFO test_helpers_end_to_end: End Router2 Output
2023-01-05T22:04:43.276185Z  INFO test_helpers_end_to_end: ****************

2023-01-05T22:04:43.285018Z  INFO test_helpers_end_to_end: ****************
2023-01-05T22:04:43.285024Z  INFO test_helpers_end_to_end: Start Ingester2 Output
2023-01-05T22:04:43.285029Z  INFO test_helpers_end_to_end: ****************
...
[iox_arrow_flight/src/encode.rs:202] out = [
    RecordBatch {
        schema: ...
        columns: [
            PrimitiveArray<Timestamp(Nanosecond, None)>
            [
              1970-01-01T00:00:00.000123456,
              1970-01-01T00:00:00.000123457,
            ],
            BooleanArray
            [
              true,
              false, (<----- this is correct)
            ],
        ],
        row_count: 2,
    },
]
2023-01-05T22:04:43.285057Z  INFO test_helpers_end_to_end: ****************
2023-01-05T22:04:43.285062Z  INFO test_helpers_end_to_end: End Ingester2 Output
2023-01-05T22:04:43.285067Z  INFO test_helpers_end_to_end: ****************

2023-01-05T22:04:43.288304Z  INFO test_helpers_end_to_end: ****************
2023-01-05T22:04:43.288309Z  INFO test_helpers_end_to_end: Start Querier2 Output
2023-01-05T22:04:43.288314Z  INFO test_helpers_end_to_end: ****************
...
2023-01-05T22:04:43.218720Z  INFO service_grpc_flight: Running SQL via flight do_get namespace_name=7035626699643192_7595499248155172 query=select * from the_table trace=
[iox_arrow_flight/src/client.rs:358] flight_data_to_arrow_batch(&data, Arc::clone(&state.schema),
    &state.dictionaries_by_field) = Ok(
    RecordBatch {
        schema: ...
        columns: [
            PrimitiveArray<Timestamp(Nanosecond, None)>
            [
              1970-01-01T00:00:00.000123456,
              1970-01-01T00:00:00.000123457,
            ],
            BooleanArray
            [
              true,
              false, (<----- this is correct)
            ],
        ],
        row_count: 2,
    },
)
[querier/src/table/mod.rs:479] partitions_result? = [
    IngesterPartition {
        ingester: "http://127.0.0.1:8090",
        ingester_uuid: Some(
            9d141b57989e46a59c8a69ba7419fe39,
        ),
        partition_id: PartitionId(
            1,
        ),
        shard_id: ShardId(
            1,
        ),
        completed_persistence_count: 0,
        parquet_max_sequence_number: None,
        tombstone_max_sequence_number: None,
        partition_sort_key: None,
        chunks: [
            IngesterChunk {
                chunk_id: ChunkId(
                    1bb2e8c906994355a608b63b52321745,
                ),
                partition_id: PartitionId(
                    1,
                ),
                schema: ...
                partition_sort_key: None,
                batches: [
                    RecordBatch {
                        schema: ...
                        columns: [
                            PrimitiveArray<Timestamp(Nanosecond, None)>
                            [
                              1970-01-01T00:00:00.000123456,
                              1970-01-01T00:00:00.000123457,
                            ],
                            BooleanArray
                            [
                              true,
                              false, (<----- this is correct)
                            ],
                        ],
                        row_count: 2,
                    },
                ],
...
                },
            },
        ],
    },
]
[iox_arrow_flight/src/encode.rs:202] out = [
    RecordBatch {
        schema: ...
        columns: [
            PrimitiveArray<Timestamp(Nanosecond, None)>
            [
              1970-01-01T00:00:00.000123456, (<----- timestamp ending in 6 is true)
            ],
            BooleanArray
            [
              true, (<----- this is correct)
            ],
        ],
        row_count: 1,
    },
]
[iox_arrow_flight/src/encode.rs:202] out = [
    RecordBatch {
        schema: ...
        columns: [
            PrimitiveArray<Timestamp(Nanosecond, None)>
            [
              1970-01-01T00:00:00.000123457, (<----- timestamp ending in 7 is false)
            ],
            BooleanArray
            [
              false, (<----- this is correct)
            ],
        ],
        row_count: 1,
    },
]
```

</details>

### CODE REVIEW

**Comment by carols10cents** [comment]
I still haven't figured out what's going on; it still doesn't make any sense.

Here's what I have figured out:

- In the end-to-end tests that use an ingester that never persists, when the querier calls `iox_arrow_flight::encode::encode_batch` to send the data it has back to the tests, `encode_batch` is getting the record batches I expect but producing `FlightData` that is NOT what I expect.
- I have tried to reproduce this behavior in a unit test in `iox_arrow_flight` and I cannot. I *believe* the tests I've added in this PR to `iox_arrow_flight/src/encode.rs` are sending the same inputs to `encode_batch` as the querier is sending `encode_batch` in the integration tests, but the unit tests are passing. I can't for the life of me figure out what is different between the two setups.
- The part of `encode_batch` that introduces the differences is `arrow_flight::utils::flight_data_from_arrow_batch`. We are currently on arrow-flight 29.0.0, and [in arrow-flight 30.0.0 this function has been deprecated](https://github.com/apache/arrow-rs/pull/3353). Also [in arrow-flight 30.0.0, `FlightData` uses `Bytes`](https://github.com/apache/arrow-rs/pull/3359). I don't think either of these are relevant here; I tried to reproduce this issue in unit tests in `arrow_flight` starting both from tag 29.0.0 and from master and I was unable to cause the problem in those tests.
- The problem isn't always flipping a `false` to a `true`; the test `boolean_weirdness_3_fails_flips_true_to_false` has a `true` flipping to `false`.
- When there are a series of boolean values, it seems like it's always the last value in the series that gets flipped.
- These failures appear to be deterministic: If they fail, they always fail in the same way.

**Comment by carols10cents** [comment]
Here's how to reproduce the problem in one integration test and fail to reproduce the problem in what I think is an identical unit test. Note that the only two `dbg!` statements currently in this PR as of the last commit are on the record batch just before it's passed in to `flight_data_from_arrow_batch` and the flight batch just after it's returned from that function.

To run the integration test, use:

```
RUST_LOG=info TEST_INTEGRATION=1 cargo test -p influxdb_iox boolean_weirdness_1
```

The test will fail with:

```
expected:

[
    "+--------------------------------+-------+",
    "| time                           | val   |",
    "+--------------------------------+-------+",
    "| 1970-01-01T00:00:00.000123456Z | true  |",
    "| 1970-01-01T00:00:00.000123457Z | false |",
    "+--------------------------------+-------+",
]
actual:

[
    "+--------------------------------+------+",
    "| time                           | val  |",
    "+--------------------------------+------+",
    "| 1970-01-01T00:00:00.000123456Z | true |",
    "| 1970-01-01T00:00:00.000123457Z | true |",
    "+--------------------------------+------+",
]
```

In the querier log output, you'll see this (I have removed boring parts and annotated interesting parts):

```
2023-01-06T22:14:37.813034Z  INFO test_helpers_end_to_end: ****************
2023-01-06T22:14:37.813039Z  INFO test_helpers_end_to_end: Start Querier2 Output
2023-01-06T22:14:37.813044Z  INFO test_helpers_end_to_end: ****************
...
[iox_arrow_flight/src/encode.rs:144] &batch = RecordBatch {
    schema: ...,
    columns: [
        PrimitiveArray<Timestamp(Nanosecond, None)>
        [
          1970-01-01T00:00:00.000123456, (<---- timestamp ending in 6)
        ],
        BooleanArray
        [
          true, (<---- true value in the input as expected)
        ],
    ],
    row_count: 1,
}
[iox_arrow_flight/src/encode.rs:146] &flight_batch = FlightData {
    flight_descriptor: None,
    data_header: [...],
    app_metadata: [],
    data_body: [
        255,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        64,
        226,
        1,
        0,
        0,
        0,
        0,
        0,
        255,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1, (<---- this is the true value)
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
}
[iox_arrow_flight/src/encode.rs:144] &batch = RecordBatch {
    schema: ...,
    columns: [
        PrimitiveArray<Timestamp(Nanosecond, None)>
        [
          1970-01-01T00:00:00.000123457, (<---- timestamp ending in 7)
        ],
        BooleanArray
        [
          false, (<---- false value in the input as expected)
        ],
    ],
    row_count: 1,
}
[iox_arrow_flight/src/encode.rs:146] &flight_batch = FlightData {
    flight_descriptor: None,
    data_header: ...,
    app_metadata: [],
    data_body: [
        255,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        65,
        226,
        1,
        0,
        0,
        0,
        0,
        0,
        255,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1, (<---- this should be 0 but instead it's set to true)
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
}
```

To run the unit test, use:

```
cargo test -p iox_arrow_flight two_batches -- --nocapture
```

The test will pass, so the `--nocapture` is needed to see the `dbg!` output.

In the test output, you'll see this (I have removed boring parts and annotated interesting parts):

```
running 1 test
[iox_arrow_flight/src/encode.rs:144] &batch = RecordBatch {
    schema: ...,
    columns: [
        PrimitiveArray<Timestamp(Nanosecond, None)>
        [
          1970-01-01T00:00:00.000123456, (<---- timestamp ending in 6)
        ],
        BooleanArray
        [
          true, (<---- true value in the input as expected)
        ],
    ],
    row_count: 1,
}
[iox_arrow_flight/src/encode.rs:146] &flight_batch = FlightData {
    flight_descriptor: None,
    data_header: [...],
    app_metadata: [],
    data_body: [
        255,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        64,
        226,
        1,
        0,
        0,
        0,
        0,
        0,
        255,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1, (<---- this is the true value)
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
}
[iox_arrow_flight/src/encode.rs:144] &batch = RecordBatch {
    schema: ...,
    columns: [
        PrimitiveArray<Timestamp(Nanosecond, None)>
        [
          1970-01-01T00:00:00.000123457, (<---- timestamp ending in 7)
        ],
        BooleanArray
        [
          false, (<---- false value in the input as expected)
        ],
    ],
    row_count: 1,
}
[iox_arrow_flight/src/encode.rs:146] &flight_batch = FlightData {
    flight_descriptor: None,
    data_header: [...],
    app_metadata: [],
    data_body: [
        255,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        65,
        226,
        1,
        0,
        0,
        0,
        0,
        0,
        255,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0, (<---- this value is 0 as expected, unlike in the integration test!!)
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
}
```

Please check all my work and assumptions, it's entirely possible that I've missed something silly but at this point I also feel like it's entirely possible there are ghosts in arrow-flight that are taunting me. 👻

**Comment by crepererum** [comment]
I think it's a slicing bug in arrow. `dbg!(batch)` shows the payload data but NOT the underlying buffers. I think in the integration tests the buffers of the two batches are shared. To confirm this I've added the following lines before `let (flight_dictionaries, flight_batch) = flight_data_from_arrow_batch(&batch, options);`:

```rust
for c in batch.columns() {
    let d = c.data();
    dbg!(d);
}
```

In the integration test this prints the same output for both batches:

```text
[iox_arrow_flight/src/encode.rs:147] d = ArrayData {
    data_type: Timestamp(
        Nanosecond,
        None,
    ),
    len: 1,
    null_count: 0,
    offset: 0,
    buffers: [
        Buffer {
            data: Bytes { ptr: 0x7fcd22c0c600, len: 16, data: [
                64,
                226,
                1,
                0,
                0,
                0,
                0,
                0,
                65,
                226,
                1,
                0,
                0,
                0,
                0,
                0,
            ] },
            offset: 0,
            length: 16,
        },
    ],
    child_data: [],
    null_bitmap: None,
}
[iox_arrow_flight/src/encode.rs:147] d = ArrayData {
    data_type: Boolean,
    len: 1,
    null_count: 0,
    offset: 0,
    buffers: [
        Buffer {
            data: Bytes { ptr: 0x7fcd22c0c680, len: 1, data: [
                1,
            ] },
            offset: 0,
            length: 1,
        },
    ],
    child_data: [],
    null_bitmap: None,
}
```

and

```text
[iox_arrow_flight/src/encode.rs:147] d = ArrayData {
    data_type: Timestamp(
        Nanosecond,
        None,
    ),
    len: 1,
    null_count: 0,
    offset: 1,
    buffers: [
        Buffer {
            data: Bytes { ptr: 0x7fcd22c0c600, len: 16, data: [
                64,
                226,
                1,
                0,
                0,
                0,
                0,
                0,
                65,
                226,
                1,
                0,
                0,
                0,
                0,
                0,
            ] },
            offset: 0,
            length: 16,
        },
    ],
    child_data: [],
    null_bitmap: None,
}
[iox_arrow_flight/src/encode.rs:147] d = ArrayData {
    data_type: Boolean,
    len: 1,
    null_count: 0,
    offset: 1,
    buffers: [
        Buffer {
            data: Bytes { ptr: 0x7fcd22c0c680, len: 1, data: [
                1,
            ] },
            offset: 0,
            length: 1,
        },
    ],
    child_data: [],
    null_bitmap: None,
}
```

Note that the buffers are the same but the offsets into them are different. Note that the `ArrayData` offsets and sizes are given in "elements / rows", while the `Buffer` sizes are given in bytes. I can replicate this in a unit test that now fails (as the integration test):

```rust
    #[tokio::test]
    async fn encode_bools() {
        let options = arrow::ipc::writer::IpcWriteOptions::default();

        let time_field = Field::new(
            "time",
            DataType::Timestamp(TimeUnit::Nanosecond, None),
            false,
        )
        .with_metadata(HashMap::from([(
            "iox::column::type".into(),
            "iox::column_type::timestamp".into(),
        )]));
        let val_bool_field =
            Field::new("val", DataType::Boolean, true).with_metadata(HashMap::from([(
                "iox::column::type".into(),
                "iox::column_type::field::boolean".into(),
            )]));

        let schema =
            Arc::new(Schema::new(vec![time_field, val_bool_field]).with_metadata(HashMap::new()));

        let times = TimestampNanosecondArray::from(vec![123456, 123457]);
        let bools = BooleanArray::from(vec![true, false]);

        let batch =
            RecordBatch::try_new(Arc::clone(&schema), vec![Arc::new(times), Arc::new(bools)])
                .unwrap();
        let batch = batch.slice(1, 1);

        let encoded: Vec<_> = encode_batch(schema, 2097152, batch, &options)
            .try_collect()
            .await
            .unwrap();
        assert_eq!(encoded.len(), 1);

        let expected_flight_data = FlightData {
            app_metadata: vec![],
            data_body: vec![
                255, 0, 0, 0, 0, 0, 0, 0, 65, 226, 1, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0,
            ],
            data_header: vec![
                16, 0, 0, 0, 12, 0, 26, 0, 24, 0, 23, 0, 4, 0, 8, 0, 12, 0, 0, 0, 32, 0, 0, 0, 32,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 4, 0, 10, 0, 20, 0, 12, 0, 8, 0, 4, 0,
                10, 0, 0, 0, 52, 0, 0, 0, 12, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0,
                0, 8, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 24, 0,
                0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
            ],
            flight_descriptor: None,
        };

        assert_eq!(encoded[0], expected_flight_data);
    }
```

**Comment by crepererum** [comment]
I'm now trying to port this test to vanilla arrow.

**Comment by crepererum** [comment]
Upstream bug: https://github.com/apache/arrow-rs/issues/3496

**Comment by carols10cents** [comment]
Thank you so much for figuring this out @crepererum ! I don't think any of these tests are particularly worthwhile; the query_test that discovered this is sufficient, so I'm closing this.

**Pull request closed without merging**
