### PR TITLE
feat: Hook up new compaction algorithm

### LINKED ISSUE #5121: Given an organized subset of L0+L1 files, compact into a set of new L1 files
Given the output of https://github.com/influxdata/influxdb_iox/issues/5120, which should be a collection of parquet files where the L1 files come first and the L0 files come after and the L0 files keep their ordering by sequence number, first:

- Log the partition ID, number (and IDs?) of L0 input files, number (and IDs?) of L1 input files, total size of input files
- Would the number of files of each level and total size make useful metrics too? Anything else?

Then compact the L0 and L1 files into a new set of L1 files with this criteria:

- If the total size of the files is < 30MB: 
  - Write everything into a single L1 file
  - This value is `INFLUXDB_IOX_COMPACTION_PERCENTAGE_MAX_FILE_SIZE * .01 * INFLUXDB_IOX_COMPACTION_MAX_DESIRED_FILE_SIZE_BYTES`, which defaults to `30 * .01 * 100 MB = 30 MB` (needs to be converted to bytes)
- If the total size is > 30MB and < 130MB: 
  - Write 80% of the data into one L1 file and 20% into another, split based on time.
  - Use the min and max times of the files and figure out the 80% point, assume data is roughly evenly distributed.
  - Percentage is `INFLUXDB_IOX_COMPACTION_SPLIT_PERCENTAGE` that defaults to 80
- If the total size is > 130MB: 
  - Determine a split based on time where files of about 100MB are output with some remainder of 10MB or so is left for the last file. 
  - Again the split should be based on time... **wait, how do we convert between approximate size and time? Just start streaming and stop when the file size goes over the limit?**
  - This value is `(1 + INFLUXDB_IOX_COMPACTION_PERCENTAGE_MAX_FILE_SIZE * .01) * INFLUXDB_IOX_COMPACTION_MAX_DESIRED_FILE_SIZE_BYTES`, which defaults to `(1 + 30 * .01) * 100 MB = 130 MB` (needs to be converted to bytes)

After completion of writing all files to object storage:

Within a transaction:

- Create records for all the new L1 files in the catalog
- Mark the input files (both L0 and L1) as to_delete = 't' in the catalog

Then:

- Log successful compaction of partition ID with the number (and IDs?) of new L1 files and the total size of those files 
- Would the number of new L1 files and their total size? Or each size? Make useful metrics?

### PR DESCRIPTION
**Pull request by carols10cents**
Closes #5121 

🚨🚨 This will turn on the new-new compaction algorithm, so don't merge this until we're ready to deploy 🚨🚨

TODO:

- There are 2 metrics on `Compactor` that aren't being used on this branch: `compaction_output_counter` and `compaction_duration`. Should they be set up and used or should they be removed? 
- Are there other metrics that we need to get useful information about how compaction is performing?

### CODE REVIEW

**Review by NGA-TRAN — APPROVED** [review]
Looks great. I have gone over this carefully.

- I have pointed out where the `compaction_duration` should go
-  Let us remove `compaction_output_counter`
- When you are done with the 2 above, you should merge this. I have modified IDPE repo to turn off Compactor. We do not have to worry it will get deployed automatically. When we are ready, I will turn Compactor on in IDPE and after that it will get deployed

**Comment by NGA-TRAN** [comment]
Hmm, clicking "Merge pull request" causes Semantic error. I will need to resolve this first

**Comment by NGA-TRAN** [comment]
And also a test failure. Let me try to create a new branch and do cherry pick and see

**Comment by carols10cents** [comment]
Closing this in favor of https://github.com/influxdata/influxdb_iox/pull/5194 !

**Pull request closed without merging**
