### PR TITLE
feat: add shard sink indirection

### PR DESCRIPTION
**Pull request by tustvold**
Adds an indirection to the shard map to allow for per-shard configuration and potentially different sink types.

Also fixes up the error scoping.

### CODE REVIEW

**Comment by mkmik** [comment]
Any reason why we want to do this now?

**Comment by tustvold** [comment]
I wanted to get the indirection in sooner, to avoid a substantial refactoring effort down the line, with API breaking changes, etc... if/when we want to support alternative sinks.

I also may be looking for a hobby project and one of the options I'm considering would be adding Kinesis support to IOx :laughing:

**Comment by mkmik** [comment]
I wonder if this indirection should sit in the "remote" map (the place that maps a node id with a url). 

This way if we end up having other code that writes to a remote, that is not based on the sharding config, we'd be able to talk to the sink using the appropriate protocol/adaptor

**Comment by mkmik** [comment]
> Every program has (at least) two purposes: the one for which it was written, and another for which it wasn't
> -- random quote in the internets

**Comment by tustvold** [comment]
> I wonder if this indirection should sit in the "remote" map (the place that maps a node id with a url).

I think it could, but a lot of that code is very IOx specific, with server IDs resolving to gRPC connection URLs, etc... which I think is a good thing to keep not overly generic. The thing is called a NodeGroup not a Sink after all :laughing: 

The bigger reason I'd like to keep it separate is to support different transport encoding, many sinks  I can think of will need to encode the data differently in order to split it across kinesis shards, kafka partitions, whatever, and I'd like to keep that option open.

> Every program has (at least) two purposes: the one for which it was written, and another for which it wasn't

I'm not sure what you're saying here...

**Comment by mkmik** [comment]
> > I wonder if this indirection should sit in the "remote" map (the place that maps a node id with a url).
> 
> I think it could, but a lot of that code is very IOx specific, with server IDs resolving to gRPC connection URLs, etc... which I think is a good thing to keep not overly generic. The thing is called a NodeGroup not a Sink after all 😆

yes, that code is currently IOx specific, because it's only used to "transport".

but if you squint the right way, it's equivalent; IIRC the only code that actually uses the "remotes" map is the sharding layer.

all you'd have to do is to just move the sink abstraction after the shard map indirection.

> 
> The bigger reason I'd like to keep it separate is to support different transport encoding, many sinks I can think of will need to encode the data differently in order to split it across kinesis shards, kafka partitions, whatever, and I'd like to keep that option open.
> 
> > Every program has (at least) two purposes: the one for which it was written, and another for which it wasn't
> 
> I'm not sure what you're saying here...

only that if you design a tool to do one thing, there will be people that will want to use it to do something different, one way or another; so yeah it's a good idea to at least be kind with those people (which could be future outselves)

**Comment by tustvold** [comment]
> but if you squint the right way, it's equivalent; IIRC the only code that actually uses the "remotes" map is the sharding layer.

Is that always going to be the case? I'd have thought once we have subscriptions and distributed query that would change?

**Comment by mkmik** [comment]
> Is that always going to be the case? I'd have thought once we have subscriptions and distributed query that would change?

you're right.

let's a have a dedicated sink abstraction.

**Review by mkmik — APPROVED** [review]

**Pull request merged**
