### PR TITLE
fix: Revert Bump dotenvy from 0.15.1 to 0.15.2 (#5450)

### PR DESCRIPTION
**Pull request by mkmik**
This reverts commit 84acbd2fad7980fbdd3e2a9b17854e92e370b6ef.

There is an upstream issue; https://github.com/allan2/dotenvy/issues/12

We need a test to make sure dependabot doesn't update the dep back to some version that hasn't fixed the upstream issue yet.

That's why I'm not c-losing #5454 in this PR.

### CODE REVIEW

**Comment by crepererum** [comment]
You can add a rule for dependabot here:

https://github.com/influxdata/influxdb_iox/blob/3220c6f88bbacc5e567bed4d9fc2b50f68ebb42e/.github/dependabot.yml#L9-L15

However we shall also prevent people from re-introducing this via a manual `cargo update` (which we often use to unbreak CI after crates were yanked from crates.io). This needs an explicit constraint in our `Cargo.toml` files:

```toml
dotenvy = ">=0.15.1,<0.15.2"
```

(cargo doesn't support "not equal")

**Review by crepererum — APPROVED** [review]
Approving to unblock prod.

**Comment by mkmik** [comment]
btw, I'm not sure I'm reading this right:

```
dotenvy = ">=0.15.1,<0.15.2"
```

doesn't this basically mean `exactly equal to 0.15.1` ?

**Comment by mkmik** [comment]
(merging now and following up with either a test or a pin)

**Pull request merged**
