### PR TITLE
chore: Update to Rust 1.61

### PR DESCRIPTION
**Pull request by carols10cents**
🎉

### CODE REVIEW

**Comment by carols10cents** [comment]
OOPS forgot about clippy 😅

**Comment by carols10cents** [comment]
Ok, it looks like there's something wrong with... jemalloc? in the doc job? I don't know how... that's a tomorrow problem...

**Comment by shepmaster** [comment]
> cc: fatal error: Killed signal terminated program cc1
>  compilation terminated.

This feels a lot like "ran out of memory and the OS killed the process". There's another error as well which [also is suggested as a memory issue](https://stackoverflow.com/a/40132053/155423):

> {standard input}: Assembler messages:
> {standard input}:308625: Warning: end of file not at end of a line; newline inserted
> {standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive

We could try:
1. reducing build parallelism
2. increasing memory on the builder

**Comment by shepmaster** [comment]
And after bumping to 6GB:

image

**Comment by alamb** [comment]
Doc builder change makes sense to me. I say :shipit:

**Review by alamb — APPROVED** [review]

**Pull request merged**
