### PR TITLE
feat: Enable gRPC reflection

### LINKED ISSUE #721: Implement API Reflection
UPDATE: Our api is not gRPC based; gRPC services are defined with a protobuf schema; gRPC supports a reflection API that allows other tools to consume the schema implemented by a server and generate various things, from dyanamic clients to API playgrounds or documentation generators.

Old goal was:

An HTTP GET to `/` should return a description of the API endpoints available. The debug output from the Router in HTTP routes should probably suffice as it's fairly descriptive and, I believe, JSON.

### PR DESCRIPTION
**Pull request by mkmik**
Closes #721

Next step: remove `scripts/grpcurl` and update documentation

Test: TODO(#1432)

### CODE REVIEW

**Review by tustvold — APPROVED** [review]
❤️

**Review by alamb — COMMENTED** [review]
I wonder if there is some way to test this in an end to end way (as written if I accidentally broke grpc reflection, I am not sure CI would catch it). Maybe just something simple in the end to end tests?

**Comment by mkmik** [comment]
> I wonder if there is some way to test this in an end to end way (as written if I accidentally broke grpc reflection, I am not sure CI would catch it). Maybe just something simple in the end to end tests?

yes, I start writing such test but then I encountered this error:

YAK HAIR OVERFLOW

image


The reflection api proto used by the tonic-is not public (it's needed in order to create a client).
We just have to add a copy of the reflection API proto in our generated_types ....

**Review by alamb — APPROVED** [review]
I agree about leaving the yak haircut for some other day.

**Comment by alamb** [comment]
(I am making a copy of the yak hair overflow for my personal collection)

**Pull request merged**
