### PR TITLE
fix(README): make docker instructions clearer

### LINKED ISSUE #909: docker build fails on main branch
__Steps to reproduce:__

1. Get fresh clone of repository
2. Run `docker build .` per the instructions in readme

__Expected behaviour:__

Docker image successfully built, docker exits with status code 0

__Actual behaviour:__

Docker exits with status code 1. I see the error output as pasted below.

__Environment info:__

* Please provide the command you used to build the project, including any `RUSTFLAGS`.

I ran `docker build .`

* System info: Run `uname -srm` or similar and copy the output here (we want to know your OS, architecture etc).

Darwin 18.7.0 x86_64

* If you're running IOx in a containerised environment then details about that would be helpful.

Docker/engine version 20.10.2

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__

Output from docker

```
Step 5/14 : RUN   --mount=type=cache,id=influxdb_iox_registry,sharing=locked,target=/usr/local/cargo/registry   --mount=type=cache,id=influxdb_iox_git,sharing=locked,target=/usr/local/cargo/git   --mount=type=cache,id=influxdb_iox_target,sharing=locked,target=/influxdb_iox/target   du -cshx /usr/local/cargo/registry /usr/local/cargo/git /influxdb_iox/target &&   cargo build --target-dir /influxdb_iox/target --release &&   cp /influxdb_iox/target/release/influxdb_iox /root/influxdb_iox &&   du -cshx /usr/local/cargo/registry /usr/local/cargo/git /influxdb_iox/target
 ---> Running in 93189d762263
du: cannot access '/usr/local/cargo/registry': No such file or directory
du: cannot access '/usr/local/cargo/git': No such file or directory
du: cannot access '/influxdb_iox/target': No such file or directory
0	total
The command '/bin/sh -c du -cshx /usr/local/cargo/registry /usr/local/cargo/git /influxdb_iox/target &&   cargo build --target-dir /influxdb_iox/target --release &&   cp /influxdb_iox/target/release/influxdb_iox /root/influxdb_iox &&   du -cshx /usr/local/cargo/registry /usr/local/cargo/git /influxdb_iox/target' returned a non-zero code: 1
```

### PR DESCRIPTION
**Pull request by jacobmarble**
Fixes #909

Turns out that BuildKit is "required", not "strongly suggested".

- [x] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

### CODE REVIEW

**Review by domodwyer — APPROVED** [review]

**Review by alamb — COMMENTED** [review]
> alamb@ip-10-0-0-124 influxdb_iox % DOCKER_BUILDKIT=1 docker build .

That was a cool experience!

**Comment by jacobmarble** [comment]
Do it twice, and it should go much faster. :)

**Comment by alamb** [comment]
> Do it twice, and it should go much faster. :)


Indeed it was ~ instantaneous

**Comment by jacobmarble** [comment]
Ha, I should have said, "make a one-line code change and build again". There are two caches involved. The first is the usual Docker layer cache, and the second is the Rust cache (code from other repositories, registry cache, target directory).

Anyhow, thanks for the complement.

**Pull request merged**
