### PR TITLE
refactor: remove output sorting from scan provider

### LINKED ISSUE #7785: Remove `ChunkTableProvider::output_sort_key`
# What
Remove `ChunkTableProvider::output_sort_key`:

https://github.com/influxdata/influxdb_iox/blob/36c1d23e19d3dd258bdc7dd350082355bbc3ed82/iox_query/src/provider.rs#L170-L171

# Why
It makes the provider more complicated than it needs to be. If a provider user wants output sorting, they should stick a logical sort to the logical plan. This (to my knowledge) only affects the compactor, so it's a minimal refactor but simplifies things. It even results in the same physical plan, just that the plan construction gets "less weird".

# How
Remove the code from the provider and change the compactor to use a more ordinary construct (similar to what the querier would do if a user uses a SQL statement like `SELECT * FROM x ORDER BY ...`), i.e. use a logical/physical plan note (that results in the same final plan).

### PR DESCRIPTION
**Pull request by crepererum**
This is somewhat a left-over from the old phys. plan construction where we tried to fold in the sorts at the right place. Now the optimizer takes care of that, so we can just express this as a standard logical node (the same as SQL and InfluxQL). This makes the plan construction a bit cleaner since the actual scan provider only performs the minimal work that is required by DataFusion and the users (SQL, InfluxQL, reorg) request what they actually need.

The tests in `iox_query::frontend::reorg::tests` that assert the tests still pass and proof that the actual physical plans are identical w/ this approach.

Closes #7785.

### CODE REVIEW

**Comment by crepererum** [comment]
Mmh, this seems to break the ingester. Looks like some messed up column handling, great...

**Comment by crepererum** [comment]
fixed, was DF's creative handling of dots in column names :roll_eyes:

**Review by NGA-TRAN — APPROVED** [review]
I am about to ask about tests but from Marco comment it sounds to me the available tests cover this

**Review by NGA-TRAN — APPROVED** [review]
I am about to ask about tests but from Marco comment it sounds to me the available tests cover this

**Review by NGA-TRAN — APPROVED** [review]
I am about to ask about tests but from Marco comment it sounds to me the available tests cover this

**Comment by alamb** [comment]
> fixed, was DF's creative handling of dots in column names 🙄

I blame SQL 😛

**Review by wolffcm — APPROVED** [review]

**Pull request merged**
