### PR TITLE
refactor: make `QueryChunk` object-safe

### PR DESCRIPTION
**Pull request by crepererum**
This makes it way easier to dyn-type database implementations. The only
real change is that we make `QueryChunk::Error` opaque. Nobody is going
to inspect that anyways, it's just printed to the user.

This is a follow-up of #4053.

Ref #3934.

### CODE REVIEW

**Comment by alamb** [comment]
LOL I was working on something similar on the train this afternoon

**Comment by crepererum** [comment]
> Love it ❤️
> 
> Do you have similar plans for QueryDatabase?

Yes.

**Review by NGA-TRAN — COMMENTED** [review]
👍

**Comment by alamb** [comment]
Follow on https://github.com/influxdata/influxdb_iox/pull/4079

**Pull request merged**
